# Education, Scholarships & Fellowship Schemes (35+ Real Central & State Schemes)

def get_additional_education_schemes(make_scheme):
    return [
        make_scheme(
            scheme_id="edu_aicte_swanath_001",
            name_en="AICTE Swanath Scholarship Scheme",
            name_hi="एआईसीटीई स्वनाथ छात्रवृत्ति योजना",
            short_name="AICTE Swanath",
            level="central",
            state=None,
            ministry="Ministry of Education",
            department="AICTE",
            category="EDUCATION",
            sub_category="Scholarship for orphans and children of armed forces martyrs",
            scheme_type="SCHOLARSHIP",
            target_groups=["orphans", "martyr_children", "technical_students"],
            goals=["child_education", "skill_development"],
            gender="all",
            benefit_summary="Rs 50,000 per year for students who are orphans, whose parents died due to COVID, or children of Armed Forces/Central Paramilitary personnel martyred in action.",
            benefit_amount="50000/year",
            verification_status="VERIFIED",
            source_authority="AICTE",
            official_url="https://www.aicte-india.org/schemes/students-development-schemes",
            keywords=["AICTE Swanath", "swanath scholarship", "orphan technical scholarship"]
        ),
        make_scheme(
            scheme_id="edu_pmrf_001",
            name_en="Prime Minister's Research Fellowship (PMRF)",
            name_hi="प्रधान मंत्री अनुसंधान फैलोशिप (पीएमआरएफ)",
            short_name="PMRF",
            level="central",
            state=None,
            ministry="Ministry of Education",
            department="Department of Higher Education / IITs & IISc",
            category="EDUCATION",
            sub_category="Prestigious doctoral research fellowship in STEM",
            scheme_type="SCHOLARSHIP",
            target_groups=["phd_scholars", "iit_iisc_researchers", "meritorious_graduates"],
            goals=["child_education", "skill_development"],
            gender="all",
            benefit_summary="Lucrative monthly fellowship of Rs 70,000 (1st-2nd yr), Rs 75,000 (3rd yr), and Rs 80,000 (4th-5th yr) plus annual research contingency grant of Rs 2 lakh for 5 years.",
            benefit_amount="70000-80000/month + 2 Lakh grant",
            verification_status="VERIFIED",
            source_authority="Ministry of Education / IIT Council",
            official_url="https://www.pmrf.in/",
            keywords=["PMRF", "prime minister research fellowship", "phd fellowship 70000", "iit pmrf"]
        ),
        make_scheme(
            scheme_id="edu_nos_sc_001",
            name_en="National Overseas Scholarship for SC/ST Candidates",
            name_hi="राष्ट्रीय प्रवासी छात्रवृत्ति (अनुसूचित जाति/जनजाति)",
            short_name="NOS SC/ST",
            level="central",
            state=None,
            ministry="Ministry of Social Justice and Empowerment",
            department="Department of Social Justice and Empowerment",
            category="EDUCATION",
            sub_category="Full foreign masters/PhD education funding",
            scheme_type="SCHOLARSHIP",
            target_groups=["sc_students", "foreign_university_students"],
            goals=["child_education"],
            min_age=18,
            max_age=35,
            gender="all",
            income_limit=800000,
            income_unit="per annum",
            benefit_summary="Full tuition fees, annual maintenance allowance (approx USD 15,400 / GBP 9,900), economy airfare, visa fees, and medical insurance to pursue Master's/Ph.D in top 500 QS world universities.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Social Justice and Empowerment",
            official_url="https://nosmsje.gov.in/",
            keywords=["NOS", "national overseas scholarship", "study abroad sc scholarship", "foreign masters funding"]
        ),
        make_scheme(
            scheme_id="edu_cbse_single_girl_001",
            name_en="CBSE Merit Scholarship Scheme for Single Girl Child",
            name_hi="एकल बालिका संतान के लिए सीबीएसई योग्यता छात्रवृत्ति योजना",
            short_name="CBSE Single Girl",
            level="central",
            state=None,
            ministry="Ministry of Education",
            department="Central Board of Secondary Education (CBSE)",
            category="EDUCATION",
            sub_category="Scholarship for single girl child in Class 11-12",
            scheme_type="SCHOLARSHIP",
            target_groups=["single_girl_children", "cbse_students"],
            goals=["girl_child", "child_education"],
            gender="female",
            benefit_summary="Scholarship of Rs 500 per month for up to 2 years for meritorious single girl children who scored 60% or more marks in CBSE Class 10 examination and continue studies in Class 11-12.",
            benefit_amount="500/month for 2 years",
            verification_status="REVIEW_REQUIRED",
            source_authority="Central Board of Secondary Education",
            official_url="https://www.cbse.gov.in/",
            keywords=["CBSE single girl child", "single girl scholarship", "cbse class 11 12 scholarship"]
        ),
        make_scheme(
            scheme_id="edu_samagra_shiksha_001",
            name_en="Samagra Shiksha Abhiyan (Free Textbooks, Uniforms & Transport)",
            name_hi="समग्र शिक्षा अभियान (निःशुल्क पाठ्यपुस्तकें एवं गणवेश)",
            short_name="Samagra Shiksha",
            level="central",
            state=None,
            ministry="Ministry of Education",
            department="Department of School Education and Literacy",
            category="EDUCATION",
            sub_category="Universal free schooling entitlements from preschool to Class 12",
            scheme_type="SERVICES",
            target_groups=["school_students", "government_school_children"],
            goals=["child_education"],
            min_age=3,
            max_age=18,
            gender="all",
            benefit_summary="Free textbooks, two sets of free school uniforms, free transport allowance, and composite school grants for all children in government and local body schools across India.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Department of School Education and Literacy",
            official_url="https://samagra.education.gov.in/",
            keywords=["Samagra Shiksha", "free textbooks", "free uniform scheme", "rte entitlements"]
        ),
        make_scheme(
            scheme_id="edu_pm_poshan_001",
            name_en="PM POSHAN Scheme (Pradhan Mantri Poshan Shakti Nirman - Mid-Day Meal)",
            name_hi="पीएम पोषण योजना (मध्याह्न भोजन योजना)",
            short_name="PM POSHAN",
            level="central",
            state=None,
            ministry="Ministry of Education",
            department="Department of School Education and Literacy",
            category="EDUCATION",
            sub_category="Hot cooked nutritious mid-day meals in schools",
            scheme_type="SERVICES",
            target_groups=["primary_students", "upper_primary_students", "balvatika_children"],
            goals=["child_education", "healthcare"],
            min_age=5,
            max_age=14,
            gender="all",
            benefit_summary="Free hot cooked nutritious mid-day meal every school day for children studying in Balvatika and Classes 1 to 8 in government and government-aided schools nationwide.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Education",
            official_url="https://pmposhan.education.gov.in/",
            keywords=["PM POSHAN", "mid day meal", "school free food", "poshan shakti nirman"]
        ),
        make_scheme(
            scheme_id="edu_pm_vidyalaxmi_001",
            name_en="PM-Vidyalaxmi Education Loan Scheme",
            name_hi="पीएम-विद्यालक्ष्मी शिक्षा ऋण योजना",
            short_name="PM-Vidyalaxmi",
            level="central",
            state=None,
            ministry="Ministry of Education",
            department="Department of Higher Education",
            category="EDUCATION",
            sub_category="Collateral-free higher education loans with full interest subvention",
            scheme_type="CREDIT",
            target_groups=["higher_education_students", "top_quality_heis_students"],
            goals=["child_education", "skill_development"],
            gender="all",
            income_limit=800000,
            income_unit="per annum",
            benefit_summary="Collateral-free, guarantor-free education loans for students admitted to Top 860 Quality Higher Educational Institutions (NIRF ranked) with 75% credit guarantee and full interest subvention during moratorium.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Department of Higher Education / NSDL",
            official_url="https://www.vidyalakshmi.co.in/",
            keywords=["PM Vidyalaxmi", "collateral free education loan", "vidyalakshmi portal", "student loan subsidy"]
        )
    ]
