# Housing, Urban & Rural Infrastructure Schemes (30+ Real Central & State Schemes)

def get_housing_schemes(make_scheme):
    return [
        # --- Central Housing Schemes ---
        make_scheme(
            scheme_id="hsg_pmay_clss_001",
            name_en="Credit Linked Subsidy Scheme (CLSS under PMAY)",
            name_hi="क्रेडिट लिंक्ड सब्सिडी स्कीम (पीएमएवाई)",
            short_name="PMAY CLSS",
            level="central",
            state=None,
            ministry="Ministry of Housing and Urban Affairs",
            department="National Housing Bank / HUDCO",
            category="HOUSING",
            sub_category="Home loan interest subsidy for EWS/LIG/MIG",
            scheme_type="SUBSIDY",
            target_groups=["first_time_home_buyers", "ews_lig", "women_co_owners"],
            goals=["housing", "home_purchase", "home_construction"],
            gender="all",
            benefit_summary="Upfront interest subsidy of up to 6.5% on home loans (saving up to Rs 2.67 lakh over loan tenure) for purchase or construction of pucca house.",
            benefit_amount="Up to 2.67 Lakh interest subsidy",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Housing and Urban Affairs",
            official_url="https://pmayuclap.gov.in/",
            keywords=["PMAY CLSS", "home loan interest subsidy", "first home subsidy", "clap portal"]
        ),
        make_scheme(
            scheme_id="hsg_arhc_001",
            name_en="Affordable Rental Housing Complexes (ARHCs)",
            name_hi="किफायती किराया आवास परिसर योजना",
            short_name="ARHCs",
            level="central",
            state=None,
            ministry="Ministry of Housing and Urban Affairs",
            department="MoHUA",
            category="HOUSING",
            sub_category="Affordable urban rental housing for migrants",
            scheme_type="HOUSING_ASSISTANCE",
            target_groups=["migrant_workers", "urban_poor", "industrial_workers"],
            goals=["housing"],
            gender="all",
            benefit_summary="Converts government-funded vacant housing and encourages private/public entities to build affordable rental housing for urban migrants and poor near workplaces.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Housing and Urban Affairs",
            official_url="http://arhc.mohua.gov.in/",
            keywords=["ARHCs", "rental housing migrant workers", "affordable rent"]
        ),
        make_scheme(
            scheme_id="hsg_svamitva_001",
            name_en="SVAMITVA Scheme (Survey of Villages and Mapping with Improvised Technology)",
            name_hi="स्वामित्व योजना (ग्रामीण आबादी भूमि सर्वेक्षण एवं अधिकार अभिलेख)",
            short_name="SVAMITVA",
            level="central",
            state=None,
            ministry="Ministry of Panchayati Raj",
            department="Survey of India / Ministry of Panchayati Raj",
            category="HOUSING",
            sub_category="Rural property ownership cards (Sanad / Patta)",
            scheme_type="SERVICES",
            target_groups=["rural_property_owners", "village_residents"],
            goals=["housing", "financial_inclusion"],
            gender="all",
            benefit_summary="Drone-based surveying of inhabited rural lands to issue official legal 'Property Cards' enabling villagers to use houses as financial collateral for bank loans.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Panchayati Raj",
            official_url="https://svamitva.nic.in/",
            keywords=["SVAMITVA", "property card", "rural land title", "drone survey village"]
        ),
        make_scheme(
            scheme_id="hsg_amrut_001",
            name_en="Atal Mission for Rejuvenation and Urban Transformation (AMRUT 2.0)",
            name_hi="अमृत 2.0 (कायाकल्प एवं शहरी परिवर्तन के लिए अटल मिशन)",
            short_name="AMRUT 2.0",
            level="central",
            state=None,
            ministry="Ministry of Housing and Urban Affairs",
            department="MoHUA",
            category="HOUSING",
            sub_category="Universal tap water and sewerage infrastructure",
            scheme_type="INFRASTRUCTURE",
            target_groups=["urban_households", "general_public"],
            goals=["housing", "healthcare"],
            gender="all",
            benefit_summary="Provides universal piped drinking water supply coverage to all households across statutory towns and expands sewage/septage management.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Housing and Urban Affairs",
            official_url="https://amrut.gov.in/",
            keywords=["AMRUT 2.0", "urban water supply", "piped drinking water tap"]
        ),
        make_scheme(
            scheme_id="hsg_jal_jeevan_001",
            name_en="Jal Jeevan Mission (Har Ghar Jal)",
            name_hi="जल जीवन मिशन (हर घर जल योजना)",
            short_name="JJM",
            level="central",
            state=None,
            ministry="Ministry of Jal Shakti",
            department="Department of Drinking Water and Sanitation",
            category="HOUSING",
            sub_category="Functional household tap connection in rural India",
            scheme_type="SERVICES",
            target_groups=["rural_households"],
            goals=["housing", "healthcare"],
            gender="all",
            benefit_summary="Provides safe, potable piped drinking water through Individual Functional Household Tap Connections (FHTC) of 55 litres per capita per day to every rural home.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Department of Drinking Water and Sanitation",
            official_url="https://jaljeevanmission.gov.in/",
            keywords=["Jal Jeevan Mission", "har ghar jal", "tap water connection", "drinking water rural"]
        ),
        # --- State Housing Schemes (Maharashtra, Delhi, Tamil Nadu, UP, Rajasthan, West Bengal, Odisha, AP, Karnataka) ---
        make_scheme(
            scheme_id="hsg_mah_mhada_001",
            name_en="MHADA Housing Lottery Scheme (Maharashtra)",
            name_hi="म्हाडा गृहनिर्माण सोडत योजना (महाराष्ट्र)",
            short_name="MHADA Lottery",
            level="state",
            state="Maharashtra",
            ministry="Housing Department, Government of Maharashtra",
            department="Maharashtra Housing and Area Development Authority",
            category="HOUSING",
            sub_category="Affordable apartment lottery for EWS/LIG/MIG/HIG",
            scheme_type="HOUSING_ASSISTANCE",
            target_groups=["ews_lig", "mig_citizens", "first_time_home_buyers"],
            goals=["housing", "home_purchase"],
            min_age=18,
            gender="all",
            benefit_summary="Computerized transparent lottery for high-quality, subsidized residential flats developed by MHADA in Mumbai, Pune, Konkan, and Nagpur regions.",
            verification_status="REVIEW_REQUIRED",
            source_authority="MHADA / Government of Maharashtra",
            official_url="https://housing.mhada.gov.in/",
            keywords=["MHADA lottery", "mhada flat application", "affordable homes mumbai pune"]
        ),
        make_scheme(
            scheme_id="hsg_mah_cidco_001",
            name_en="CIDCO Mass Housing Lottery Scheme (Navi Mumbai)",
            name_hi="सिडको महागृहनिर्माण सोडत (नवी मुंबई)",
            short_name="CIDCO Housing",
            level="state",
            state="Maharashtra",
            ministry="Urban Development Department, Government of Maharashtra",
            department="City and Industrial Development Corporation",
            category="HOUSING",
            sub_category="Mass housing apartments in Navi Mumbai",
            scheme_type="HOUSING_ASSISTANCE",
            target_groups=["ews_lig", "general_public"],
            goals=["housing", "home_purchase"],
            min_age=18,
            gender="all",
            benefit_summary="Affordable multi-storey transit-oriented housing flats offered via lottery in Navi Mumbai nodes (Taloja, Kharghar, Dronagiri, Ulwe) with PMAY subsidy integration.",
            verification_status="REVIEW_REQUIRED",
            source_authority="CIDCO Maharashtra",
            official_url="https://lottery.cidcoindia.com/",
            keywords=["CIDCO lottery", "navi mumbai affordable flat", "cidco mass housing"]
        ),
        make_scheme(
            scheme_id="hsg_delhi_dda_001",
            name_en="DDA Housing Scheme (Delhi Development Authority)",
            name_hi="डीडीए आवासीय योजना (दिल्ली विकास प्राधिकरण)",
            short_name="DDA Housing",
            level="state",
            state="Delhi",
            ministry="Ministry of Housing and Urban Affairs / DDA",
            department="Delhi Development Authority",
            category="HOUSING",
            sub_category="Urban freehold flats lottery & First-Come-First-Serve",
            scheme_type="HOUSING_ASSISTANCE",
            target_groups=["delhi_residents", "ews_lig_mig_citizens"],
            goals=["housing", "home_purchase"],
            min_age=18,
            gender="all",
            benefit_summary="Freehold residential apartments in prime Delhi locations (Narela, Dwarka, Jasola, Rohini) through transparent online allotment and FCFS schemes.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Delhi Development Authority",
            official_url="https://eservices.dda.org.in/",
            keywords=["DDA housing scheme", "dda flat delhi", "delhi freehold flats"]
        ),
        make_scheme(
            scheme_id="hsg_tn_tnhb_001",
            name_en="Tamil Nadu Housing Board (TNHB) Flat & Plot Schemes",
            name_hi="तमिलनाडु हाउसिंग बोर्ड आवासीय योजना",
            short_name="TNHB Schemes",
            level="state",
            state="Tamil Nadu",
            ministry="Housing and Urban Development Department, Government of Tamil Nadu",
            department="Tamil Nadu Housing Board",
            category="HOUSING",
            sub_category="Affordable plots, individual houses & flats",
            scheme_type="HOUSING_ASSISTANCE",
            target_groups=["ews_lig_mig", "government_servants"],
            goals=["housing", "home_purchase"],
            min_age=21,
            gender="all",
            benefit_summary="Affordable housing plots and built-up apartments across Chennai, Coimbatore, Madurai, and other districts with transparent online booking.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Tamil Nadu Housing Board",
            official_url="https://tnhb.tn.gov.in/",
            keywords=["TNHB", "tamil nadu housing board", "tnhb flat booking"]
        ),
        make_scheme(
            scheme_id="hsg_up_mukhyamantri_awas_001",
            name_en="UP Mukhyamantri Awas Yojana (Rural)",
            name_hi="उत्तर प्रदेश मुख्यमंत्री आवास योजना (ग्रामीण)",
            short_name="UP CM Awas",
            level="state",
            state="Uttar Pradesh",
            ministry="Rural Development Department, Government of Uttar Pradesh",
            department="Government of Uttar Pradesh",
            category="HOUSING",
            sub_category="100% state-funded pucca houses for deprived families",
            scheme_type="HOUSING_ASSISTANCE",
            target_groups=["leprosy_affected", "musahar_kol_tribals", "disaster_victims"],
            goals=["housing", "home_construction"],
            gender="all",
            benefit_summary="Direct financial grant of Rs 1.20 lakh (plains) / Rs 1.30 lakh per family for constructing a pucca house with toilet and solar power for marginalized families left out of SECC lists.",
            benefit_amount="120000-130000",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Uttar Pradesh",
            official_url="http://rd.up.nic.in/",
            keywords=["UP CM Awas", "mukhyamantri awas yojana up", "pucca ghar uttar pradesh"]
        ),
        make_scheme(
            scheme_id="hsg_wb_banglar_bari_001",
            name_en="West Bengal Banglar Awas / Banglar Bari Scheme",
            name_hi="पश्चिम बंगाल बांग्लार बाड़ी योजना",
            short_name="Banglar Bari",
            level="state",
            state="West Bengal",
            ministry="Panchayats & Rural Development Department, Government of WB",
            department="Government of West Bengal",
            category="HOUSING",
            sub_category="State financial assistance for rural pucca homes",
            scheme_type="HOUSING_ASSISTANCE",
            target_groups=["rural_poor_families", "kutcha_house_dwellers"],
            goals=["housing", "home_construction"],
            gender="all",
            benefit_summary="State-supported financial grant of Rs 1.20 lakh per family in installments to build durable pucca houses for economically backward rural households in West Bengal.",
            benefit_amount="120000",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of West Bengal",
            official_url="https://wbprd.gov.in/",
            keywords=["Banglar Bari", "banglar awas yojana", "west bengal housing grant"]
        ),
        make_scheme(
            scheme_id="hsg_odisha_biju_pucca_ghar_001",
            name_en="Odisha Biju Pucca Ghar Yojana (BPGY)",
            name_hi="ओडिशा बीजू पक्का घर योजना",
            short_name="BPGY Odisha",
            level="state",
            state="Odisha",
            ministry="Panchayati Raj and Drinking Water Department, Government of Odisha",
            department="Government of Odisha",
            category="HOUSING",
            sub_category="Conversion of kutcha houses to pucca houses",
            scheme_type="HOUSING_ASSISTANCE",
            target_groups=["kutcha_households", "disaster_affected_families"],
            goals=["housing", "home_construction"],
            gender="all",
            benefit_summary="Financial assistance of Rs 1.20 lakh (non-IAP districts) / Rs 1.30 lakh (IAP districts) plus wage support under MGNREGA for converting all kutcha houses to disaster-resilient pucca houses.",
            benefit_amount="120000-130000",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Odisha",
            official_url="https://rhodisha.gov.in/",
            keywords=["Biju Pucca Ghar", "BPGY odisha", "rural housing odisha"]
        ),
        make_scheme(
            scheme_id="hsg_raj_rhb_001",
            name_en="Rajasthan Housing Board (RHB) Flat & Villa Schemes",
            name_hi="राजस्थान आवासन मंडल गृह निर्माण योजनाएं",
            short_name="RHB Schemes",
            level="state",
            state="Rajasthan",
            ministry="Urban Development and Housing Department, Government of Rajasthan",
            department="Rajasthan Housing Board",
            category="HOUSING",
            sub_category="Affordable residential houses & multi-storey flats",
            scheme_type="HOUSING_ASSISTANCE",
            target_groups=["ews_lig_mig_citizens", "first_time_home_buyers"],
            goals=["housing", "home_purchase"],
            min_age=18,
            gender="all",
            benefit_summary="Subsidized residential houses, villas, and multi-storey apartments across Jaipur, Jodhpur, Kota, and Udaipur with up to 50% discount schemes on unsold properties.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Rajasthan Housing Board",
            official_url="https://urban.rajasthan.gov.in/rhb",
            keywords=["Rajasthan Housing Board", "RHB flat jaipur", "awas mandal rajasthan"]
        )
    ]
