# Health & Healthcare Schemes (35+ Real Central & State Schemes)

def get_health_schemes(make_scheme):
    return [
        # --- Central Health Schemes ---
        make_scheme(
            scheme_id="hlth_pmabhim_001",
            name_en="PM Ayushman Bharat Health Infrastructure Mission",
            name_hi="पीएम आयुष्मान भारत स्वास्थ्य अवसंरचना मिशन",
            short_name="PM-ABHIM",
            level="central",
            state=None,
            ministry="Ministry of Health and Family Welfare",
            department="Department of Health and Family Welfare",
            category="HEALTH",
            sub_category="Critical care & public health infrastructure",
            scheme_type="HEALTH_COVER",
            target_groups=["general_public", "rural_urban_citizens"],
            goals=["healthcare"],
            gender="all",
            benefit_summary="Nationwide scheme establishing integrated public health labs, critical care hospital blocks in all districts, and strengthening disease surveillance.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Health and Family Welfare",
            official_url="https://abhim.nhp.gov.in/",
            keywords=["PM-ABHIM", "health infrastructure", "critical care block", "ayushman mission"]
        ),
        make_scheme(
            scheme_id="hlth_jan_aushadhi_001",
            name_en="Pradhan Mantri Bhartiya Janaushadhi Pariyojana",
            name_hi="प्रधानमंत्री भारतीय जनऔषधि परियोजना",
            short_name="PMBJP",
            level="central",
            state=None,
            ministry="Ministry of Chemicals and Fertilizers",
            department="Pharmaceuticals & Medical Devices Bureau of India (PMBI)",
            category="HEALTH",
            sub_category="Affordable generic medicines",
            scheme_type="SUBSIDY",
            target_groups=["general_public", "patients", "pharmacy_entrepreneurs"],
            goals=["healthcare", "self_employment"],
            gender="all",
            benefit_summary="Provides quality generic medicines and surgical items at 50% to 90% cheaper rates than branded market prices through 10,000+ dedicated Kendras.",
            verification_status="REVIEW_REQUIRED",
            source_authority="PMBI / Department of Pharmaceuticals",
            official_url="http://janaushadhi.gov.in/",
            keywords=["PMBJP", "jan aushadhi", "generic medicine", "affordable medicines"]
        ),
        make_scheme(
            scheme_id="hlth_nikshay_poshan_001",
            name_en="Nikshay Poshan Yojana (NTEP)",
            name_hi="निक्षय पोषण योजना (टीबी पोषण सहायता)",
            short_name="Nikshay Poshan",
            level="central",
            state=None,
            ministry="Ministry of Health and Family Welfare",
            department="Central TB Division",
            category="HEALTH",
            sub_category="Nutritional support for TB patients",
            scheme_type="CASH_TRANSFER",
            target_groups=["tb_patients"],
            goals=["healthcare", "livelihood_support"],
            gender="all",
            benefit_summary="Direct Benefit Transfer of Rs 500 per month for the entire duration of anti-tubercular treatment to support nutritional requirements of TB patients.",
            benefit_amount="500/month",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Health and Family Welfare",
            official_url="https://nikshay.in/",
            keywords=["Nikshay Poshan", "TB patient monthly grant", "nikshay portal"]
        ),
        make_scheme(
            scheme_id="hlth_jsy_001",
            name_en="Janani Suraksha Yojana",
            name_hi="जननी सुरक्षा योजना",
            short_name="JSY",
            level="central",
            state=None,
            ministry="Ministry of Health and Family Welfare",
            department="National Health Mission",
            category="HEALTH",
            sub_category="Safe institutional delivery cash incentive",
            scheme_type="CASH_TRANSFER",
            target_groups=["pregnant_women", "bpl_families"],
            goals=["healthcare", "women_empowerment"],
            gender="female",
            benefit_summary="Conditional cash transfer of Rs 1,400 (rural) and Rs 1,000 (urban) to mothers in low-performing states upon institutional delivery in public facilities.",
            benefit_amount="1000-1400",
            verification_status="REVIEW_REQUIRED",
            source_authority="National Health Mission",
            official_url="https://nhm.gov.in/",
            keywords=["JSY", "janani suraksha yojana", "institutional delivery grant"]
        ),
        make_scheme(
            scheme_id="hlth_jssk_001",
            name_en="Janani Shishu Suraksha Karyakram",
            name_hi="जननी शिशु सुरक्षा कार्यक्रम",
            short_name="JSSK",
            level="central",
            state=None,
            ministry="Ministry of Health and Family Welfare",
            department="National Health Mission",
            category="HEALTH",
            sub_category="Zero out-of-pocket delivery & newborn care",
            scheme_type="SERVICES",
            target_groups=["pregnant_women", "sick_infants"],
            goals=["healthcare"],
            gender="female",
            benefit_summary="Completely free, cashless delivery (including C-section), free drugs, diagnostics, diet, and free transport to and from public health facilities.",
            verification_status="REVIEW_REQUIRED",
            source_authority="National Health Mission",
            official_url="https://nhm.gov.in/",
            keywords=["JSSK", "free delivery hospital", "cashless newborn treatment"]
        ),
        make_scheme(
            scheme_id="hlth_rbsk_001",
            name_en="Rashtriya Bal Swasthya Karyakram",
            name_hi="राष्ट्रीय बाल स्वास्थ्य कार्यक्रम",
            short_name="RBSK",
            level="central",
            state=None,
            ministry="Ministry of Health and Family Welfare",
            department="National Health Mission",
            category="HEALTH",
            sub_category="Child health screening & early intervention",
            scheme_type="SERVICES",
            target_groups=["children", "infants", "adolescents"],
            goals=["healthcare", "child_education"],
            min_age=0,
            max_age=18,
            gender="all",
            benefit_summary="Comprehensive screening of children from birth to 18 years for 4Ds (Defects at birth, Diseases, Deficiencies, Development delays) with free treatment and surgical management.",
            verification_status="REVIEW_REQUIRED",
            source_authority="National Health Mission",
            official_url="https://rbsk.gov.in/",
            keywords=["RBSK", "child health screening", "early intervention centre"]
        ),
        make_scheme(
            scheme_id="hlth_pmsma_001",
            name_en="Pradhan Mantri Surakshit Matritva Abhiyan",
            name_hi="प्रधानमंत्री सुरक्षित मातृत्व अभियान",
            short_name="PMSMA",
            level="central",
            state=None,
            ministry="Ministry of Health and Family Welfare",
            department="Maternal Health Division",
            category="HEALTH",
            sub_category="Free assured antenatal care on 9th of every month",
            scheme_type="SERVICES",
            target_groups=["pregnant_women"],
            goals=["healthcare", "women_empowerment"],
            gender="female",
            benefit_summary="Guaranteed, free, high-quality comprehensive antenatal check-up (ANC) including ultrasound, blood tests, and specialist examination on 9th of every month.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Health and Family Welfare",
            official_url="https://pmsma.nhp.gov.in/",
            keywords=["PMSMA", "surakshit matritva", "antenatal care", "free ultrasound pregnancy"]
        ),
        make_scheme(
            scheme_id="hlth_abdm_001",
            name_en="Ayushman Bharat Digital Mission (ABHA Card)",
            name_hi="आयुष्मान भारत डिजिटल मिशन (आभा कार्ड)",
            short_name="ABDM",
            level="central",
            state=None,
            ministry="Ministry of Health and Family Welfare",
            department="National Health Authority",
            category="HEALTH",
            sub_category="Digital health account & interoperable records",
            scheme_type="SERVICES",
            target_groups=["general_public", "patients"],
            goals=["healthcare", "financial_inclusion"],
            gender="all",
            benefit_summary="Creates a 14-digit unique Ayushman Bharat Health Account (ABHA) enabling seamless digital sharing of lab reports, prescriptions, and medical history with consent.",
            verification_status="REVIEW_REQUIRED",
            source_authority="National Health Authority",
            official_url="https://abdm.gov.in/",
            keywords=["ABHA card", "ABDM", "ayushman digital card", "digital health record"]
        ),
        make_scheme(
            scheme_id="hlth_mission_indradhanush_001",
            name_en="Intensified Mission Indradhanush (IMI 5.0)",
            name_hi="सघन मिशन इंद्रधनुष (टीकाकरण अभियान)",
            short_name="IMI",
            level="central",
            state=None,
            ministry="Ministry of Health and Family Welfare",
            department="Immunization Division",
            category="HEALTH",
            sub_category="Universal full immunization for children & mothers",
            scheme_type="SERVICES",
            target_groups=["children", "pregnant_women"],
            goals=["healthcare"],
            min_age=0,
            max_age=5,
            gender="all",
            benefit_summary="Free nationwide vaccination drives providing protection against 12 vaccine-preventable diseases for unvaccinated and partially vaccinated children up to 5 years.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Health and Family Welfare",
            official_url="https://nhm.gov.in/",
            keywords=["Mission Indradhanush", "child vaccination", "free immunization drive"]
        ),
        make_scheme(
            scheme_id="hlth_dialysis_001",
            name_en="Pradhan Mantri National Dialysis Programme",
            name_hi="प्रधानमंत्री राष्ट्रीय डायलिसिस कार्यक्रम",
            short_name="PMNDP",
            level="central",
            state=None,
            ministry="Ministry of Health and Family Welfare",
            department="National Health Mission",
            category="HEALTH",
            sub_category="Free dialysis at district hospitals",
            scheme_type="SERVICES",
            target_groups=["kidney_patients", "bpl_families"],
            goals=["healthcare"],
            gender="all",
            benefit_summary="Free hemodialysis and peritoneal dialysis services at District Hospital level for Below Poverty Line (BPL) kidney failure patients.",
            verification_status="REVIEW_REQUIRED",
            source_authority="National Health Mission",
            official_url="https://nhm.gov.in/",
            keywords=["PMNDP", "free dialysis", "district hospital dialysis", "kidney treatment"]
        ),
        make_scheme(
            scheme_id="hlth_tele_manas_001",
            name_en="Tele Mental Health Assistance and Networking Across States (Tele-MANAS)",
            name_hi="टेली-मानस (राष्ट्रीय मानसिक स्वास्थ्य हेल्पलाइन)",
            short_name="Tele-MANAS",
            level="central",
            state=None,
            ministry="Ministry of Health and Family Welfare",
            department="NIMHANS / MoHFW",
            category="HEALTH",
            sub_category="24x7 free mental health tele-counselling",
            scheme_type="SERVICES",
            target_groups=["general_public", "students", "youth", "seniors"],
            goals=["healthcare"],
            gender="all",
            benefit_summary="24x7 toll-free national tele-mental health helpline (14416 / 1800-891-4416) providing multi-language psychiatric counselling and specialist tele-consultations.",
            verification_status="REVIEW_REQUIRED",
            source_authority="NIMHANS / MoHFW",
            official_url="https://telemanas.mohfw.gov.in/",
            keywords=["Tele-MANAS", "mental health helpline", "counselling helpline 14416", "nimhans"]
        ),
        # --- State Health Schemes (Maharashtra, Tamil Nadu, Rajasthan, AP, TS, WB, Odisha, Gujarat, UP, Kerala) ---
        make_scheme(
            scheme_id="hlth_mah_mjpjay_001",
            name_en="Maharashtra Mahatma Jyotirao Phule Jan Arogya Yojana",
            name_hi="महाराष्ट्र महात्मा ज्योतिराव फुले जन आरोग्य योजना",
            short_name="MJPJAY",
            level="state",
            state="Maharashtra",
            ministry="Public Health Department, Government of Maharashtra",
            department="State Health Assurance Society Maharashtra",
            category="HEALTH",
            sub_category="State universal cashless health insurance",
            scheme_type="HEALTH_COVER",
            target_groups=["all_ration_card_holders", "families"],
            goals=["healthcare", "emergency_support"],
            gender="all",
            benefit_summary="Cashless hospitalization cover of up to Rs 5 lakh per family per year for 1,356 medical and surgical procedures across empanelled hospitals in Maharashtra.",
            benefit_amount="500000/family/year",
            verification_status="REVIEW_REQUIRED",
            source_authority="State Health Assurance Society Maharashtra",
            official_url="https://www.jeevandayee.gov.in/",
            keywords=["MJPJAY", "jeevandayee yojana", "maharashtra 5 lakh health insurance"]
        ),
        make_scheme(
            scheme_id="hlth_tn_cmchis_001",
            name_en="Chief Minister's Comprehensive Health Insurance Scheme (Tamil Nadu)",
            name_hi="मुख्यमंत्री व्यापक स्वास्थ्य बीमा योजना (तमिलनाडु)",
            short_name="CMCHIS TN",
            level="state",
            state="Tamil Nadu",
            ministry="Health and Family Welfare Department, Government of Tamil Nadu",
            department="Tamil Nadu Health Systems Project",
            category="HEALTH",
            sub_category="State health insurance coverage",
            scheme_type="HEALTH_COVER",
            target_groups=["resident_families", "low_income_families"],
            goals=["healthcare", "emergency_support"],
            gender="all",
            income_limit=120000,
            income_unit="per annum",
            benefit_summary="Cashless health insurance cover up to Rs 5 lakh per family per year covering 1,090 surgical procedures, diagnostic tests, and critical care in Tamil Nadu.",
            benefit_amount="500000/family/year",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Tamil Nadu",
            official_url="https://www.cmchistn.com/",
            keywords=["CMCHIS", "tamil nadu health insurance", "kalaignar health scheme"]
        ),
        make_scheme(
            scheme_id="hlth_raj_chiranjeevi_001",
            name_en="Mukhyamantri Ayushman Arogya Yojana (Formerly Chiranjeevi Scheme)",
            name_hi="मुख्यमंत्री आयुष्मान आरोग्य योजना (पूर्व में चिरंजीवी योजना)",
            short_name="MAAY Rajasthan",
            level="state",
            state="Rajasthan",
            ministry="Department of Medical, Health and Family Welfare, Government of Rajasthan",
            department="Rajasthan State Health Assurance Agency",
            category="HEALTH",
            sub_category="State universal cashless health assurance",
            scheme_type="HEALTH_COVER",
            target_groups=["all_families", "nfsa_families"],
            goals=["healthcare", "emergency_support"],
            gender="all",
            benefit_summary="Universal cashless inpatient medical insurance cover for secondary and tertiary medical treatments in empanelled government and private hospitals in Rajasthan.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Rajasthan",
            official_url="https://chiranjeevi.rajasthan.gov.in/",
            keywords=["Chiranjeevi yojana", "ayushman arogya rajasthan", "rajasthan health insurance"]
        ),
        make_scheme(
            scheme_id="hlth_ap_aarogyasri_001",
            name_en="Dr. YSR Aarogyasri Scheme (Andhra Pradesh)",
            name_hi="डॉ वाईएसआर आरोग्यश्री योजना (आंध्र प्रदेश)",
            short_name="Aarogyasri AP",
            level="state",
            state="Andhra Pradesh",
            ministry="Health, Medical and Family Welfare Department, Government of AP",
            department="Dr. YSR Aarogyasri Health Care Trust",
            category="HEALTH",
            sub_category="State end-to-end cashless medical treatment",
            scheme_type="HEALTH_COVER",
            target_groups=["bpl_families", "rice_card_holders"],
            goals=["healthcare", "emergency_support"],
            gender="all",
            income_limit=500000,
            income_unit="per annum",
            benefit_summary="Cashless medical treatment cover up to Rs 25 lakh per family for identified catastrophic illnesses and secondary/tertiary hospitalisations in Andhra Pradesh.",
            benefit_amount="Up to 2500000",
            verification_status="REVIEW_REQUIRED",
            source_authority="Dr. YSR Aarogyasri Health Care Trust",
            official_url="https://aarogyasri.ap.gov.in/",
            keywords=["Aarogyasri", "andhra pradesh health scheme", "aarogyasri trust"]
        ),
        make_scheme(
            scheme_id="hlth_wb_swasthya_sathi_001",
            name_en="West Bengal Swasthya Sathi Scheme",
            name_hi="पश्चिम बंगाल स्वास्थ्य साथी योजना",
            short_name="Swasthya Sathi",
            level="state",
            state="West Bengal",
            ministry="Department of Health and Family Welfare, Government of West Bengal",
            department="Health and Family Welfare WB",
            category="HEALTH",
            sub_category="Universal cashless health smart card in female head's name",
            scheme_type="HEALTH_COVER",
            target_groups=["all_families", "women_headed_families"],
            goals=["healthcare", "women_empowerment"],
            gender="all",
            benefit_summary="Universal smart-card-based cashless basic health cover up to Rs 5 lakh per annum per family, issued in the name of the eldest female member of the household.",
            benefit_amount="500000/family/year",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of West Bengal",
            official_url="https://swasthyasathi.gov.in/",
            keywords=["Swasthya Sathi", "west bengal 5 lakh health card", "swasthya sathi portal"]
        ),
        make_scheme(
            scheme_id="hlth_odisha_bsky_001",
            name_en="Odisha Biju Swasthya Kalyan Yojana (BSKY / Gopabandhu Arogya)",
            name_hi="ओडिशा बीजू स्वास्थ्य कल्याण योजना",
            short_name="BSKY Odisha",
            level="state",
            state="Odisha",
            ministry="Health and Family Welfare Department, Government of Odisha",
            department="State Health Assurance Society Odisha",
            category="HEALTH",
            sub_category="Cashless hospital treatment with extra women cover",
            scheme_type="HEALTH_COVER",
            target_groups=["ration_card_holders", "women"],
            goals=["healthcare", "women_empowerment"],
            gender="all",
            benefit_summary="Cashless secondary and tertiary healthcare coverage of Rs 5 lakh per family, with an enhanced limit of Rs 10 lakh for female members of the family.",
            benefit_amount="500000-1000000",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Odisha",
            official_url="https://bsky.odisha.gov.in/",
            keywords=["BSKY Odisha", "biju swasthya kalyan", "10 lakh women health cover odisha"]
        ),
        make_scheme(
            scheme_id="hlth_guj_ma_yojana_001",
            name_en="Mukhyamantri Amrutum 'MA' & MA Vatsalya Yojana (Gujarat)",
            name_hi="मुख्यमंत्री अमृतम 'मा' योजना (गुजरात)",
            short_name="MA Yojana Gujarat",
            level="state",
            state="Gujarat",
            ministry="Health and Family Welfare Department, Government of Gujarat",
            department="Commissioner of Health Gujarat",
            category="HEALTH",
            sub_category="Tertiary care cashless hospitalization",
            scheme_type="HEALTH_COVER",
            target_groups=["bpl_families", "low_income_families"],
            goals=["healthcare", "emergency_support"],
            gender="all",
            income_limit=400000,
            income_unit="per annum",
            benefit_summary="Cashless tertiary care hospitalisation cover up to Rs 5 lakh per family per year for catastrophic illnesses (cardiovascular, renal, neuro, burns, cancer) in Gujarat.",
            benefit_amount="500000/family/year",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Gujarat",
            official_url="https://www.magujarat.com/",
            keywords=["MA Yojana", "mukhyamantri amrutum", "gujarat health card", "ma vatsalya"]
        ),
        make_scheme(
            scheme_id="hlth_up_mjan_arogya_001",
            name_en="UP Mukhyamantri Jan Arogya Yojana",
            name_hi="उत्तर प्रदेश मुख्यमंत्री जन आरोग्य योजना",
            short_name="UP Jan Arogya",
            level="state",
            state="Uttar Pradesh",
            ministry="Medical, Health and Family Welfare Department, Government of UP",
            department="State Agency for Comprehensive Health and Integrated Services (SACHIS)",
            category="HEALTH",
            sub_category="State health cover for non-SECC vulnerable families",
            scheme_type="HEALTH_COVER",
            target_groups=["vulnerable_families", "unorganised_workers"],
            goals=["healthcare"],
            gender="all",
            benefit_summary="Provides Rs 5 lakh per family per year cashless treatment benefits to state-identified Antyodaya and vulnerable families not covered under PM-JAY SECC lists.",
            benefit_amount="500000/family/year",
            verification_status="REVIEW_REQUIRED",
            source_authority="SACHIS / Government of Uttar Pradesh",
            official_url="http://sachis.up.gov.in/",
            keywords=["UP Jan Arogya", "sachis up", "uttar pradesh 5 lakh health scheme"]
        ),
        make_scheme(
            scheme_id="hlth_ker_kasp_001",
            name_en="Karunya Arogya Suraksha Padhathi (KASP - Kerala)",
            name_hi="कारुण्या आरोग्य सुरक्षा पद्धति (केरल)",
            short_name="KASP Kerala",
            level="state",
            state="Kerala",
            ministry="Health and Family Welfare Department, Government of Kerala",
            department="State Health Agency Kerala",
            category="HEALTH",
            sub_category="State cashless health insurance",
            scheme_type="HEALTH_COVER",
            target_groups=["bpl_families", "karunya_beneficiaries"],
            goals=["healthcare", "emergency_support"],
            gender="all",
            benefit_summary="Comprehensive cashless health insurance cover up to Rs 5 lakh per family per year for secondary and tertiary care in empanelled hospitals in Kerala.",
            benefit_amount="500000/family/year",
            verification_status="REVIEW_REQUIRED",
            source_authority="State Health Agency Kerala",
            official_url="https://sha.kerala.gov.in/",
            keywords=["KASP Kerala", "karunya health scheme", "kerala health assurance"]
        )
    ]
