# Social Security, Disability & Senior Citizens Schemes (40+ Real Central & State Schemes)

def get_social_security_schemes(make_scheme):
    return [
        # --- Central Social Security & Disability Schemes ---
        make_scheme(
            scheme_id="soc_adip_001",
            name_en="Scheme of Assistance to Disabled Persons for Purchase/Fitting of Aids and Appliances (ADIP)",
            name_hi="दिव्यांगजनों को सहायक उपकरण खरीद/फिटिंग सहायता योजना (एडिप)",
            short_name="ADIP Scheme",
            level="central",
            state=None,
            ministry="Ministry of Social Justice and Empowerment",
            department="Department of Empowerment of Persons with Disabilities (DEPwD)",
            category="DISABILITY",
            sub_category="Free modern assistive devices & cochlear implants",
            scheme_type="SERVICES",
            target_groups=["persons_with_disabilities", "divyangjan"],
            goals=["disability_support", "healthcare"],
            gender="all",
            income_limit=360000,
            income_unit="per annum",
            disability_requirement="Minimum 40% disability (UDID card)",
            benefit_summary="Free distribution of modern aids and high-tech appliances (motorized tricycles, smart canes, digital hearing aids, prosthetics, and cochlear implants up to Rs 6 lakh).",
            verification_status="REVIEW_REQUIRED",
            source_authority="ALIMCO / DEPwD",
            official_url="https://alimco.in/",
            keywords=["ADIP scheme", "free wheelchair divyang", "cochlear implant grant", "alimco aids"]
        ),
        make_scheme(
            scheme_id="soc_rashtriya_vayoshri_001",
            name_en="Rashtriya Vayoshri Yojana (RVY)",
            name_hi="राष्ट्रीय वयोश्री योजना",
            short_name="Rashtriya Vayoshri",
            level="central",
            state=None,
            ministry="Ministry of Social Justice and Empowerment",
            department="Department of Social Justice and Empowerment",
            category="SENIOR_CITIZEN",
            sub_category="Free physical aids for senior citizens",
            scheme_type="SERVICES",
            target_groups=["senior_citizens", "bpl_seniors"],
            goals=["old_age_support", "healthcare"],
            min_age=60,
            gender="all",
            benefit_summary="Free provision of age-related physical aids and assisted-living devices (walking sticks, elbow crutches, walkers, tripods, hearing aids, wheelchairs, dentures, and spectacles) to BPL senior citizens.",
            verification_status="REVIEW_REQUIRED",
            source_authority="ALIMCO / Ministry of Social Justice",
            official_url="https://alimco.in/",
            keywords=["Rashtriya Vayoshri", "senior citizen free spectacles hearing aid", "rvy alimco"]
        ),
        make_scheme(
            scheme_id="soc_udid_card_001",
            name_en="Unique Disability ID (UDID) Project",
            name_hi="विशिष्ट दिव्यांगता पहचान पत्र (यूडीआईडी कार्ड)",
            short_name="UDID Card",
            level="central",
            state=None,
            ministry="Ministry of Social Justice and Empowerment",
            department="Department of Empowerment of Persons with Disabilities (DEPwD)",
            category="DISABILITY",
            sub_category="Single pan-India disability identity document",
            scheme_type="SERVICES",
            target_groups=["persons_with_disabilities"],
            goals=["disability_support", "financial_inclusion"],
            gender="all",
            disability_requirement="Any of 21 benchmark disabilities under RPwD Act 2016",
            benefit_summary="National online database creating a single universal photo ID card for persons with disabilities, enabling pan-India validation for all government concessions, pensions, and transport discounts.",
            verification_status="REVIEW_REQUIRED",
            source_authority="DEPwD / Ministry of Social Justice",
            official_url="https://www.swavlambancard.gov.in/",
            keywords=["UDID card", "swavlamban card", "disability certificate online", "divyang card"]
        ),
        make_scheme(
            scheme_id="soc_nfbs_001",
            name_en="National Family Benefit Scheme (NFBS under NSAP)",
            name_hi="राष्ट्रीय परिवार लाभ योजना",
            short_name="NFBS",
            level="central",
            state=None,
            ministry="Ministry of Rural Development",
            department="NSAP Division",
            category="SOCIAL_SECURITY",
            sub_category="Lump-sum cash grant upon death of primary breadwinner",
            scheme_type="CASH_TRANSFER",
            target_groups=["bpl_families", "bereaved_families"],
            goals=["family_support", "social_security"],
            gender="all",
            benefit_summary="One-time lump-sum financial assistance of Rs 20,000 to a Below Poverty Line (BPL) household upon the death of the primary breadwinner (aged 18-59 years).",
            benefit_amount="20000 one-time",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Rural Development",
            official_url="https://nsap.nic.in/",
            keywords=["NFBS", "national family benefit scheme", "death of breadwinner grant"]
        ),
        make_scheme(
            scheme_id="soc_annapurna_001",
            name_en="Annapurna Scheme (under NSAP)",
            name_hi="अन्नपूर्णा योजना",
            short_name="Annapurna NSAP",
            level="central",
            state=None,
            ministry="Ministry of Rural Development / Ministry of Consumer Affairs",
            department="Department of Food and Public Distribution",
            category="SENIOR_CITIZEN",
            sub_category="Free monthly foodgrains for destitute seniors",
            scheme_type="SOCIAL_ASSISTANCE",
            target_groups=["destitute_seniors", "unpensioned_seniors"],
            goals=["old_age_support"],
            min_age=65,
            gender="all",
            benefit_summary="Provides 10 kg of foodgrains (wheat/rice) completely free of charge per month to destitute senior citizens aged 65 and above who are not receiving any pension under NOAPS.",
            benefit_amount="10 kg free foodgrains/month",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Rural Development",
            official_url="https://nsap.nic.in/",
            keywords=["Annapurna scheme", "10 kg free ration senior citizen", "destitute old age food"]
        ),
        # --- State Social Security & Pension Schemes (Maharashtra, UP, Rajasthan, Tamil Nadu, Odisha, Telangana, AP, WB) ---
        make_scheme(
            scheme_id="soc_mah_sanjay_gandhi_001",
            name_en="Maharashtra Sanjay Gandhi Niradhar Anudan Yojana",
            name_hi="महाराष्ट्र संजय गांधी निराधार अनुदान योजना",
            short_name="Sanjay Gandhi Niradhar",
            level="state",
            state="Maharashtra",
            ministry="Social Justice and Special Assistance Department, Government of Maharashtra",
            department="Social Welfare Commissionerate Maharashtra",
            category="SOCIAL_SECURITY",
            sub_category="Monthly financial assistance for destitute, disabled, and single women",
            scheme_type="CASH_TRANSFER",
            target_groups=["destitute_persons", "widows", "divyangjan", "transgenders"],
            goals=["social_security", "disability_support", "widow_support"],
            gender="all",
            income_limit=50000,
            income_unit="per annum",
            benefit_summary="Monthly pension of Rs 1,500 for a single beneficiary (and Rs 2,500 if there are 2 or more beneficiaries in a family) for destitute individuals, blind/disabled, and abandoned women in Maharashtra.",
            benefit_amount="1500-2500/month",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Maharashtra",
            official_url="https://sjsa.maharashtra.gov.in/",
            keywords=["Sanjay Gandhi Niradhar", "maharashtra destitute pension 1500", "sjsa maharashtra"]
        ),
        make_scheme(
            scheme_id="soc_mah_shravanbal_001",
            name_en="Maharashtra Shravanbal Seva Rajya Nivruttivetan Yojana",
            name_hi="महाराष्ट्र श्रावणबाळ सेवा राज्य निवृत्तीवेतन योजना",
            short_name="Shravanbal Yojana",
            level="state",
            state="Maharashtra",
            ministry="Social Justice and Special Assistance Department, Government of Maharashtra",
            department="Social Welfare Commissionerate Maharashtra",
            category="SENIOR_CITIZEN",
            sub_category="Old age pension for non-BPL and BPL senior citizens",
            scheme_type="CASH_TRANSFER",
            target_groups=["senior_citizens"],
            goals=["old_age_support", "pension"],
            min_age=65,
            gender="all",
            income_limit=50000,
            income_unit="per annum",
            benefit_summary="Monthly old age pension of Rs 1,500 to senior citizens aged 65 and above residing in Maharashtra whose annual family income does not exceed Rs 50,000.",
            benefit_amount="1500/month",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Maharashtra",
            official_url="https://sjsa.maharashtra.gov.in/",
            keywords=["Shravanbal yojana", "maharashtra old age pension", "shravanbal 1500"]
        ),
        make_scheme(
            scheme_id="soc_up_vridhavastha_001",
            name_en="UP Vridhavastha Pension Yojana (Old Age Pension)",
            name_hi="उत्तर प्रदेश वृद्धावस्था पेंशन योजना",
            short_name="UP Old Age Pension",
            level="state",
            state="Uttar Pradesh",
            ministry="Social Welfare Department, Government of Uttar Pradesh",
            department="Directorate of Social Welfare UP",
            category="SENIOR_CITIZEN",
            sub_category="State monthly old age pension",
            scheme_type="CASH_TRANSFER",
            target_groups=["senior_citizens", "bpl_seniors"],
            goals=["old_age_support", "pension"],
            min_age=60,
            gender="all",
            income_limit=56460,
            income_unit="per annum",
            benefit_summary="Monthly direct cash pension of Rs 1,000 per month deposited quarterly (Rs 3,000 per quarter) into bank accounts of eligible senior citizens aged 60+ in Uttar Pradesh.",
            benefit_amount="1000/month",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Uttar Pradesh",
            official_url="https://sspy-up.gov.in/",
            keywords=["UP old age pension", "sspy up portal", "vridha pension up 1000"]
        ),
        make_scheme(
            scheme_id="soc_up_divyang_pension_001",
            name_en="UP Divyangjan Pension Yojana (Disability Pension)",
            name_hi="उत्तर प्रदेश दिव्यांगजन पेंशन योजना",
            short_name="UP Divyang Pension",
            level="state",
            state="Uttar Pradesh",
            ministry="Empowerment of Persons with Disabilities Department, Government of UP",
            department="Government of Uttar Pradesh",
            category="DISABILITY",
            sub_category="State monthly disability pension",
            scheme_type="CASH_TRANSFER",
            target_groups=["persons_with_disabilities"],
            goals=["disability_support", "social_security"],
            min_age=18,
            gender="all",
            disability_requirement="Minimum 40% disability",
            benefit_summary="Monthly pension of Rs 1,000 deposited quarterly into bank accounts of persons with 40% or more disability living below poverty line in Uttar Pradesh.",
            benefit_amount="1000/month",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Uttar Pradesh",
            official_url="https://sspy-up.gov.in/",
            keywords=["UP divyang pension", "viklang pension up", "sspy disability pension"]
        ),
        make_scheme(
            scheme_id="soc_raj_ssp_pension_001",
            name_en="Rajasthan Social Security Pension Scheme (SSP Portal)",
            name_hi="राजस्थान सामाजिक सुरक्षा पेंशन योजना",
            short_name="SSP Rajasthan",
            level="state",
            state="Rajasthan",
            ministry="Social Justice and Empowerment Department, Government of Rajasthan",
            department="Government of Rajasthan",
            category="SOCIAL_SECURITY",
            sub_category="Unified state monthly pensions with mandatory 15% annual increment",
            scheme_type="CASH_TRANSFER",
            target_groups=["elderly", "widows", "specially_abled", "small_farmers"],
            goals=["old_age_support", "widow_support", "disability_support"],
            min_age=55,
            gender="all",
            income_limit=48000,
            income_unit="per annum",
            benefit_summary="Minimum assured pension of Rs 1,150 per month (increasing automatically by 15% every year under Rajasthan Minimum Income Guarantee Act) for elderly, widows, and disabled.",
            benefit_amount="Min 1150/month (auto-escalating)",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Rajasthan",
            official_url="https://ssp.rajasthan.gov.in/",
            keywords=["SSP Rajasthan", "rajasthan social security pension", "raj ssp portal"]
        ),
        make_scheme(
            scheme_id="soc_tn_oap_001",
            name_en="Tamil Nadu Old Age Pension Scheme (Indira Gandhi OAP / Destitute)",
            name_hi="तमिलनाडु वृद्धावस्था पेंशन योजना",
            short_name="TN OAP",
            level="state",
            state="Tamil Nadu",
            ministry="Revenue and Disaster Management Department, Government of Tamil Nadu",
            department="Commissioner of Social Security Schemes TN",
            category="SENIOR_CITIZEN",
            sub_category="State monthly destitute old age pension",
            scheme_type="CASH_TRANSFER",
            target_groups=["destitute_seniors", "poor_elderly"],
            goals=["old_age_support", "pension"],
            min_age=60,
            gender="all",
            benefit_summary="Monthly cash pension of Rs 1,000 deposited through direct bank transfer or doorstep delivery for destitute senior citizens aged 60 and above in Tamil Nadu.",
            benefit_amount="1000/month",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Tamil Nadu",
            official_url="https://www.tn.gov.in/",
            keywords=["Tamil Nadu OAP", "destitute pension tamil nadu", "tn social security pension"]
        ),
        make_scheme(
            scheme_id="soc_odisha_madhu_babu_001",
            name_en="Odisha Madhu Babu Pension Yojana (MBPY)",
            name_hi="ओडिशा मधु बाबू पेंशन योजना",
            short_name="MBPY Odisha",
            level="state",
            state="Odisha",
            ministry="Social Security & Empowerment of Persons with Disabilities Department, Govt of Odisha",
            department="SSEPD Odisha",
            category="SOCIAL_SECURITY",
            sub_category="Comprehensive destitute, old age & disability monthly pension",
            scheme_type="CASH_TRANSFER",
            target_groups=["destitute_seniors", "widows", "persons_with_disabilities", "transgenders"],
            goals=["old_age_support", "widow_support", "disability_support"],
            min_age=60,
            gender="all",
            income_limit=60000,
            income_unit="per annum",
            benefit_summary="Monthly social security pension ranging from Rs 1,000 to Rs 1,400 per month (depending on age 60-79 vs 80+) for elderly, widows, PwDs, and transgender persons in Odisha.",
            benefit_amount="1000-1400/month",
            verification_status="REVIEW_REQUIRED",
            source_authority="SSEPD Odisha",
            official_url="https://ssepd.odisha.gov.in/",
            keywords=["Madhu Babu pension", "MBPY odisha", "ssepd odisha portal"]
        ),
        make_scheme(
            scheme_id="soc_ts_asara_pension_001",
            name_en="Telangana Aasara Pensions",
            name_hi="तेलंगाना आसरा पेंशन योजना",
            short_name="Aasara Telangana",
            level="state",
            state="Telangana",
            ministry="Panchayat Raj and Rural Development Department, Government of Telangana",
            department="Society for Elimination of Rural Poverty (SERP)",
            category="SOCIAL_SECURITY",
            sub_category="High-value monthly pension for vulnerable groups",
            scheme_type="CASH_TRANSFER",
            target_groups=["elderly", "widows", "disabled", "beedi_workers", "toddy_tappers", "weavers"],
            goals=["old_age_support", "widow_support", "disability_support"],
            min_age=57,
            gender="all",
            benefit_summary="Substantial monthly pension of Rs 2,016 per month for elderly (57+ yrs), widows, and weavers; and Rs 3,016 per month for persons with disabilities in Telangana.",
            benefit_amount="2016-3016/month",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Telangana",
            official_url="https://aasara.telangana.gov.in/",
            keywords=["Aasara pension", "telangana 2016 pension", "aasara serp portal"]
        ),
        make_scheme(
            scheme_id="soc_ap_pension_kanuka_001",
            name_en="Andhra Pradesh YSR Pension Kanuka",
            name_hi="आंध्र प्रदेश वाईएसआर पेंशन कनुका",
            short_name="YSR Pension Kanuka",
            level="state",
            state="Andhra Pradesh",
            ministry="Panchayat Raj & Rural Development Department, Government of Andhra Pradesh",
            department="SERP Andhra Pradesh",
            category="SOCIAL_SECURITY",
            sub_category="Doorstep monthly cash pension",
            scheme_type="CASH_TRANSFER",
            target_groups=["old_age", "widows", "disabled", "dialysis_patients"],
            goals=["old_age_support", "widow_support", "disability_support"],
            min_age=60,
            gender="all",
            benefit_summary="Doorstep delivery of monthly pension of Rs 3,000 per month for elderly and widows, and up to Rs 6,000 to Rs 10,000 for severe disability and chronic kidney dialysis patients in AP.",
            benefit_amount="3000-10000/month",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Andhra Pradesh",
            official_url="https://sspensions.ap.gov.in/",
            keywords=["YSR Pension Kanuka", "andhra 3000 pension", "doorstep pension ap"]
        )
    ]
