# Business, MSME & Entrepreneurship Schemes (40+ Real Central & State Schemes)

def get_business_msme_schemes(make_scheme):
    return [
        # --- Central MSME & Business Schemes ---
        make_scheme(
            scheme_id="biz_pmegp_001",
            name_en="Prime Minister's Employment Generation Programme",
            name_hi="प्रधानमंत्री रोजगार सृजन कार्यक्रम",
            short_name="PMEGP",
            level="central",
            state=None,
            ministry="Ministry of Micro, Small and Medium Enterprises",
            department="Khadi and Village Industries Commission (KVIC)",
            category="BUSINESS",
            sub_category="Credit-linked margin money subsidy for new micro units",
            scheme_type="SUBSIDY",
            target_groups=["first_time_entrepreneurs", "rural_urban_youth", "women_sc_st"],
            goals=["business", "self_employment"],
            min_age=18,
            gender="all",
            benefit_summary="Credit-linked subsidy of 15% to 35% on project costs up to Rs 50 lakh for manufacturing units and Rs 20 lakh for service units.",
            benefit_amount="Up to 35% margin money subsidy",
            verification_status="REVIEW_REQUIRED",
            source_authority="KVIC / Ministry of MSME",
            official_url="https://www.kviconline.gov.in/pmegpeportal/",
            keywords=["PMEGP", "pmegp loan subsidy", "kvic loan", "business setup grant"]
        ),
        make_scheme(
            scheme_id="biz_cgtmse_001",
            name_en="Credit Guarantee Fund Trust for Micro and Small Enterprises",
            name_hi="सूक्ष्म एवं लघु उद्यमों के लिए क्रेडिट गारंटी फंड ट्रस्ट",
            short_name="CGTMSE",
            level="central",
            state=None,
            ministry="Ministry of Micro, Small and Medium Enterprises",
            department="SIDBI / Ministry of MSME",
            category="BUSINESS",
            sub_category="Collateral-free business loan guarantee",
            scheme_type="CREDIT",
            target_groups=["msme_entrepreneurs", "women_entrepreneurs", "sc_st_msmes"],
            goals=["business", "self_employment"],
            gender="all",
            benefit_summary="Third-party credit guarantee cover of up to 85% for collateral-free bank credit up to Rs 5 crore for new and existing Micro & Small enterprises.",
            benefit_amount="Guarantee up to Rs 5 Crore",
            verification_status="REVIEW_REQUIRED",
            source_authority="CGTMSE / SIDBI",
            official_url="https://www.cgtmse.in/",
            keywords=["CGTMSE", "collateral free loan", "msme bank loan guarantee"]
        ),
        make_scheme(
            scheme_id="biz_sfurti_001",
            name_en="Scheme of Fund for Regeneration of Traditional Industries",
            name_hi="पारंपरिक उद्योगों के उत्थान के लिए निधि योजना",
            short_name="SFURTI",
            level="central",
            state=None,
            ministry="Ministry of Micro, Small and Medium Enterprises",
            department="Ministry of MSME",
            category="BUSINESS",
            sub_category="Traditional cluster modernization grant",
            scheme_type="GRANT",
            target_groups=["artisans", "handloom_weavers", "craft_clusters"],
            goals=["business", "self_employment"],
            gender="all",
            benefit_summary="Financial assistance of up to Rs 2.5 crore (Regular cluster) / Rs 5 crore (Major cluster) for establishing Common Facility Centres, modern tooling, and design value-chains.",
            benefit_amount="Up to Rs 5 Crore per cluster",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of MSME",
            official_url="https://sfurti.msme.gov.in/",
            keywords=["SFURTI", "traditional industry cluster", "artisan common facility"]
        ),
        make_scheme(
            scheme_id="biz_aspire_001",
            name_en="ASPIRE (Scheme for Promotion of Innovation, Rural Industry & Entrepreneurship)",
            name_hi="एस्पायर (नवाचार, ग्रामीण उद्योग एवं उद्यमिता संवर्धन योजना)",
            short_name="ASPIRE",
            level="central",
            state=None,
            ministry="Ministry of Micro, Small and Medium Enterprises",
            department="Ministry of MSME",
            category="BUSINESS",
            sub_category="Livelihood business incubators & fund of funds",
            scheme_type="GRANT",
            target_groups=["rural_entrepreneurs", "agri_startups", "incubators"],
            goals=["business", "self_employment", "skill_development"],
            gender="all",
            benefit_summary="One-time 100% grant of up to Rs 1 crore to establish Livelihood Business Incubators (LBI) in agro-rural sectors, creating new micro-enterprises.",
            benefit_amount="Up to Rs 1 Crore for LBI",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of MSME",
            official_url="https://aspire.msme.gov.in/",
            keywords=["ASPIRE scheme", "livelihood business incubator", "rural startup grant"]
        ),
        make_scheme(
            scheme_id="biz_zed_001",
            name_en="MSME Sustainable (ZED) Certification Scheme",
            name_hi="एमएसएमई सतत (जेड) प्रमाणन योजना (जीरो डिफेक्ट जीरो इफेक्ट)",
            short_name="MSME ZED",
            level="central",
            state=None,
            ministry="Ministry of Micro, Small and Medium Enterprises",
            department="Quality Council of India / MSME",
            category="BUSINESS",
            sub_category="Quality certification & clean tech subsidy",
            scheme_type="SUBSIDY",
            target_groups=["manufacturing_msmes"],
            goals=["business"],
            gender="all",
            benefit_summary="Financial subsidy of up to 80% (Micro), 60% (Small), and 50% (Medium) on ZED certification cost, plus additional 10% for women/SC/ST/NER enterprises.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of MSME / QCI",
            official_url="https://zed.msme.gov.in/",
            keywords=["MSME ZED", "zero defect zero effect", "zed certification subsidy"]
        ),
        make_scheme(
            scheme_id="biz_champions_001",
            name_en="MSME Champions Scheme (Design, IPR & Incubation)",
            name_hi="एमएसएमई चैंपियंस योजना (डिजाइन, आईपीआर एवं इन्क्यूबेशन)",
            short_name="MSME Champions",
            level="central",
            state=None,
            ministry="Ministry of Micro, Small and Medium Enterprises",
            department="Office of DC MSME",
            category="BUSINESS",
            sub_category="Design assistance, patent grant & idea incubation",
            scheme_type="GRANT",
            target_groups=["msme_innovators", "startups", "students"],
            goals=["business", "skill_development"],
            gender="all",
            benefit_summary="Financial grant up to Rs 15 lakh per approved innovative idea, up to Rs 40 lakh for student/design projects, and reimbursement of patent/trademark filing fees.",
            benefit_amount="Up to 15-40 Lakh per project",
            verification_status="REVIEW_REQUIRED",
            source_authority="Office of DC MSME",
            official_url="https://champions.gov.in/",
            keywords=["MSME Champions", "patent reimbursement msme", "incubation grant"]
        ),
        make_scheme(
            scheme_id="biz_cgssd_001",
            name_en="Credit Guarantee Scheme for Subordinate Debt (CGSSD)",
            name_hi="अधीनस्थ ऋण के लिए क्रेडिट गारंटी योजना",
            short_name="CGSSD",
            level="central",
            state=None,
            ministry="Ministry of Micro, Small and Medium Enterprises",
            department="CGTMSE / Ministry of MSME",
            category="BUSINESS",
            sub_category="Debt revival for stressed and NPA MSMEs",
            scheme_type="CREDIT",
            target_groups=["stressed_msmes", "npa_promoters"],
            goals=["business"],
            gender="all",
            benefit_summary="Promoters of stressed/NPA MSME units given credit support equal to 15% of their stake (max Rs 75 lakh) with 90% credit guarantee from CGTMSE.",
            benefit_amount="Up to Rs 75 Lakh",
            verification_status="REVIEW_REQUIRED",
            source_authority="CGTMSE / Ministry of MSME",
            official_url="https://www.cgtmse.in/",
            keywords=["CGSSD", "subordinate debt msme", "stressed msme revival loan"]
        ),
        make_scheme(
            scheme_id="biz_treds_001",
            name_en="Trade Receivables Discounting System (TReDS)",
            name_hi="व्यापार प्राप्य छूट प्रणाली (टीआरईडीएस)",
            short_name="TReDS",
            level="central",
            state=None,
            ministry="Ministry of Finance / Ministry of MSME",
            department="Reserve Bank of India (RBI)",
            category="BUSINESS",
            sub_category="Online invoice discounting & working capital",
            scheme_type="FINANCIAL_SERVICES",
            target_groups=["msme_suppliers", "corporate_buyers"],
            goals=["business"],
            gender="all",
            benefit_summary="Institutional electronic platform enabling MSMEs to auction and discount trade invoices/bills against large buyers and PSUs through multiple financiers at competitive rates.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Reserve Bank of India",
            official_url="https://www.rbi.org.in/",
            keywords=["TReDS", "invoice discounting", "msme bill discounting", "rbi treds"]
        ),
        # --- State Business & MSME Schemes ---
        make_scheme(
            scheme_id="biz_up_yuva_swarozgar_001",
            name_en="UP Mukhyamantri Yuva Swarozgar Yojana",
            name_hi="उत्तर प्रदेश मुख्यमंत्री युवा स्वरोजगार योजना",
            short_name="UP Yuva Swarozgar",
            level="state",
            state="Uttar Pradesh",
            ministry="Department of MSME and Export Promotion, Government of Uttar Pradesh",
            department="Directorate of Industries UP",
            category="BUSINESS",
            sub_category="Margin money loan subsidy for youth businesses",
            scheme_type="SUBSIDY",
            target_groups=["educated_unemployed_youth"],
            goals=["business", "self_employment"],
            min_age=18,
            max_age=40,
            gender="all",
            benefit_summary="Loans up to Rs 25 lakh for manufacturing and Rs 10 lakh for service sector with 25% state margin money subsidy (max Rs 6.25 lakh).",
            benefit_amount="25% subsidy (up to 6.25 Lakh)",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Uttar Pradesh",
            official_url="http://diupmsme.upsdc.gov.in/",
            keywords=["UP Yuva Swarozgar", "up msme loan subsidy", "diupmsme portal"]
        ),
        make_scheme(
            scheme_id="biz_bihar_udyami_001",
            name_en="Bihar Mukhyamantri Udyami Yojana (SC/ST/EBC/Women/Yuva)",
            name_hi="बिहार मुख्यमंत्री उद्यमी योजना",
            short_name="Bihar Udyami",
            level="state",
            state="Bihar",
            ministry="Department of Industries, Government of Bihar",
            department="Government of Bihar",
            category="BUSINESS",
            sub_category="10 lakh enterprise package (50% grant + 50% interest-free loan)",
            scheme_type="GRANT",
            target_groups=["women_entrepreneurs", "sc_st_youth", "ebc_youth"],
            goals=["business", "self_employment", "women_empowerment"],
            min_age=18,
            max_age=50,
            gender="all",
            benefit_summary="Package of Rs 10 lakh for starting a new industrial enterprise: Rs 5 lakh as 100% grant/subsidy and Rs 5 lakh as interest-free loan (1% for general men) repayable in 84 instalments.",
            benefit_amount="10 Lakh (5 Lakh Grant + 5 Lakh Loan)",
            verification_status="REVIEW_REQUIRED",
            source_authority="Department of Industries Bihar",
            official_url="https://udyami.bihar.gov.in/",
            keywords=["Bihar Udyami Yojana", "bihar 10 lakh business loan", "udyami bihar portal"]
        ),
        make_scheme(
            scheme_id="biz_tn_needs_001",
            name_en="New Entrepreneur-cum-Enterprise Development Scheme (NEEDS - Tamil Nadu)",
            name_hi="नवीन उद्यमी एवं उद्यम विकास योजना (नीड्स - तमिलनाडु)",
            short_name="NEEDS TN",
            level="state",
            state="Tamil Nadu",
            ministry="Micro, Small and Medium Enterprises Department, Government of Tamil Nadu",
            department="Directorate of Industries and Commerce TN",
            category="BUSINESS",
            sub_category="Capital subsidy & interest subvention for first-gen entrepreneurs",
            scheme_type="SUBSIDY",
            target_groups=["first_generation_entrepreneurs", "graduates", "diploma_holders"],
            goals=["business", "self_employment"],
            min_age=21,
            max_age=45,
            gender="all",
            benefit_summary="25% capital subsidy (up to Rs 75 lakh) on project cost between Rs 10 lakh and Rs 5 crore, plus 3% interest subvention for educated first-generation entrepreneurs.",
            benefit_amount="Up to Rs 75 Lakh subsidy",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Tamil Nadu",
            official_url="https://www.msmeonline.tn.gov.in/",
            keywords=["NEEDS scheme TN", "tamil nadu entrepreneur subsidy", "msmeonline tn"]
        ),
        make_scheme(
            scheme_id="biz_mah_psi_001",
            name_en="Maharashtra Package Scheme of Incentives (PSI for MSME)",
            name_hi="महाराष्ट्र प्रोत्साहन योजना पैकेज (एमएसएमई पीएसआई)",
            short_name="Maharashtra PSI",
            level="state",
            state="Maharashtra",
            ministry="Industries Department, Government of Maharashtra",
            department="Directorate of Industries Maharashtra",
            category="BUSINESS",
            sub_category="Industrial promotion subsidy & electricity duty exemption",
            scheme_type="SUBSIDY",
            target_groups=["manufacturing_msmes", "industrial_investors"],
            goals=["business"],
            gender="all",
            benefit_summary="Basket of financial incentives including SGST reimbursement up to 100% of Fixed Capital Investment, 5% interest subsidy, and electricity duty exemption for 7-10 years.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Maharashtra",
            official_url="https://di.maharashtra.gov.in/",
            keywords=["Maharashtra PSI", "package scheme of incentives msme", "maharashtra industrial policy"]
        ),
        make_scheme(
            scheme_id="biz_raj_mlupy_001",
            name_en="Rajasthan Mukhyamantri Laghu Udyog Protsahan Yojana (MLUPY)",
            name_hi="राजस्थान मुख्यमंत्री लघु उद्योग प्रोत्साहन योजना",
            short_name="MLUPY Rajasthan",
            level="state",
            state="Rajasthan",
            ministry="Industries and Commerce Department, Government of Rajasthan",
            department="Directorate of Industries Rajasthan",
            category="BUSINESS",
            sub_category="Interest subsidy on loans up to Rs 10 crore",
            scheme_type="SUBSIDY",
            target_groups=["micro_small_entrepreneurs", "service_enterprises"],
            goals=["business", "self_employment"],
            min_age=18,
            gender="all",
            benefit_summary="Substantial interest subsidy of 8% on loans up to Rs 25 lakh, 6% on loans up to Rs 5 crore, and 5% on loans up to Rs 10 crore for setting up new manufacturing/service ventures in Rajasthan.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Rajasthan",
            official_url="https://industries.rajasthan.gov.in/",
            keywords=["MLUPY", "rajasthan msme loan subsidy", "laghu udyog protsahan yojana"]
        ),
        make_scheme(
            scheme_id="biz_guj_msme_incentive_001",
            name_en="Gujarat MSME Capital Investment & Interest Subsidy Scheme",
            name_hi="गुजरात एमएसएमई पूंजी निवेश एवं ब्याज सहायता योजना",
            short_name="Gujarat MSME Scheme",
            level="state",
            state="Gujarat",
            ministry="Industries and Mines Department, Government of Gujarat",
            department="Industries Commissionerate Gujarat",
            category="BUSINESS",
            sub_category="Capital investment subsidy & term loan interest subsidy",
            scheme_type="SUBSIDY",
            target_groups=["manufacturing_enterprises", "young_entrepreneurs"],
            goals=["business"],
            gender="all",
            benefit_summary="Capital investment subsidy up to 25% of eligible plant and machinery (max Rs 35 lakh) and interest subsidy of 5% to 7% per annum on term loans for 5-7 years in Gujarat.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Gujarat",
            official_url="https://ic.gujarat.gov.in/",
            keywords=["Gujarat MSME subsidy", "capital subsidy gujarat", "industries commissionerate gujarat"]
        )
    ]
