# Financial Inclusion, Banking & Small Savings Schemes (20+ Real Central Schemes)

def get_financial_inclusion_schemes(make_scheme):
    return [
        make_scheme(
            scheme_id="fin_po_rd_001",
            name_en="National Savings Recurring Deposit Account (Post Office 5-Year RD)",
            name_hi="राष्ट्रीय बचत आवर्ती जमा खाता (डाकघर 5 वर्षीय आरडी)",
            short_name="Post Office RD",
            level="central",
            state=None,
            ministry="Ministry of Finance / Ministry of Communications",
            department="Department of Economic Affairs / India Post",
            category="SAVINGS",
            sub_category="Monthly recurring savings deposit",
            scheme_type="SAVINGS",
            target_groups=["general_public", "small_savers", "first_time_savers"],
            goals=["short_term_savings", "long_term_savings"],
            gender="all",
            residency="Resident Indian individual",
            minimum_contribution=100,
            maximum_contribution=None,
            contribution_frequency="monthly (multiples of Rs 10)",
            lock_in="3 years (premature closure)",
            maturity="5 years (extendable by 5 years)",
            interest_rate="6.7% p.a. compounded quarterly",
            return_type="fixed_govt_notified",
            benefit_summary="Safe 5-year recurring deposit scheme offering 6.7% p.a. sovereign guaranteed return with loan facility up to 50% of credit balance after 1 year.",
            liquidity_level="medium",
            withdrawal_rules="Premature closure allowed after 3 years from account opening date.",
            verification_status="VERIFIED",
            source_authority="Department of Economic Affairs / India Post",
            official_url="https://www.indiapost.gov.in/Financial/pages/content/post-office-saving-schemes.aspx",
            keywords=["Post Office RD", "recurring deposit post office", "monthly savings scheme 100"]
        ),
        make_scheme(
            scheme_id="fin_po_td_5yr_001",
            name_en="National Savings Time Deposit Account (Post Office 5-Year TD)",
            name_hi="राष्ट्रीय बचत सावधि जमा खाता (डाकघर 5 वर्षीय टीडी)",
            short_name="Post Office 5Y TD",
            level="central",
            state=None,
            ministry="Ministry of Finance / Ministry of Communications",
            department="Department of Economic Affairs / India Post",
            category="SAVINGS",
            sub_category="Fixed-term deposit with 80C tax benefit",
            scheme_type="SAVINGS",
            target_groups=["general_public", "tax_savers"],
            goals=["short_term_savings", "long_term_savings"],
            gender="all",
            residency="Resident Indian individual",
            minimum_contribution=1000,
            maximum_contribution=None,
            contribution_frequency="one-time (multiples of Rs 100)",
            lock_in="5 years",
            maturity="5 years",
            interest_rate="7.5% p.a. paid annually",
            return_type="fixed_govt_notified",
            benefit_summary="Fixed 5-year term deposit offering 7.5% p.a. sovereign interest with Section 80C tax deduction benefit on investment.",
            tax_benefit="Section 80C on investment",
            liquidity_level="low",
            withdrawal_rules="Premature closure allowed after 6 months with post office savings rate penalty.",
            verification_status="VERIFIED",
            source_authority="Department of Economic Affairs / India Post",
            official_url="https://www.indiapost.gov.in/Financial/pages/content/post-office-saving-schemes.aspx",
            keywords=["Post Office TD", "5 year fixed deposit post office", "80C post office term deposit"]
        ),
        make_scheme(
            scheme_id="fin_po_savings_account_001",
            name_en="Post Office Savings Account (POSA)",
            name_hi="डाकघर बचत खाता",
            short_name="POSA",
            level="central",
            state=None,
            ministry="Ministry of Communications",
            department="Department of Posts",
            category="SAVINGS",
            sub_category="Liquid basic savings account with tax exemption",
            scheme_type="SAVINGS",
            target_groups=["general_public", "rural_citizens"],
            goals=["short_term_savings", "emergency_support"],
            gender="all",
            residency="Resident Indian individual",
            minimum_contribution=500,
            maximum_contribution=None,
            contribution_frequency="anytime",
            lock_in="None",
            maturity="Open-ended",
            interest_rate="4.0% p.a.",
            return_type="fixed_govt_notified",
            benefit_summary="Basic liquid savings account with ATM card, mobile banking, and Section 10(15)(i) tax exemption on interest up to Rs 3,500/year (Rs 7,000 for joint account).",
            tax_benefit="Section 10(15)(i) interest exempt up to Rs 3500",
            liquidity_level="high",
            withdrawal_rules="Anytime withdrawal at any post office branch or ATM across India.",
            verification_status="VERIFIED",
            source_authority="Department of Posts",
            official_url="https://www.indiapost.gov.in/Financial/pages/content/post-office-saving-schemes.aspx",
            keywords=["POSA", "post office savings account", "tax free interest 3500"]
        ),
        make_scheme(
            scheme_id="fin_sgb_001",
            name_en="Sovereign Gold Bond Scheme (SGB)",
            name_hi="सॉवरेन गोल्ड बॉन्ड योजना (एसजीबी)",
            short_name="SGB",
            level="central",
            state=None,
            ministry="Ministry of Finance",
            department="Reserve Bank of India (RBI)",
            category="SAVINGS",
            sub_category="Government gold bond with interest payout",
            scheme_type="SAVINGS",
            target_groups=["investors", "gold_savers", "general_public"],
            goals=["long_term_savings"],
            gender="all",
            residency="Resident Indian entity",
            minimum_contribution=1,
            maximum_contribution=4000,
            contribution_frequency="periodic tranches",
            lock_in="5 years (exit option)",
            maturity="8 years",
            interest_rate="2.50% p.a. fixed interest + Gold capital appreciation",
            return_type="sovereign_gold_linked",
            benefit_summary="Government securities denominated in grams of gold paying 2.50% fixed annual interest with 100% Capital Gains Tax exemption on redemption after 8 years.",
            tax_benefit="100% LTCG tax exempt on redemption",
            liquidity_level="medium",
            withdrawal_rules="Premature redemption permitted from 5th year on interest payment dates, or tradable on stock exchanges.",
            verification_status="VERIFIED",
            source_authority="Reserve Bank of India",
            official_url="https://www.rbi.org.in/",
            keywords=["SGB", "sovereign gold bond", "gold investment tax free", "rbi gold bond"]
        ),
        make_scheme(
            scheme_id="fin_ippb_account_001",
            name_en="India Post Payments Bank (IPPB) Doorstep Digital Account",
            name_hi="इंडिया पोस्ट पेमेंट्स बैंक (आईपीपीबी) डोरस्टेप डिजिटल खाता",
            short_name="IPPB Account",
            level="central",
            state=None,
            ministry="Ministry of Communications",
            department="Department of Posts",
            category="FINANCIAL_INCLUSION",
            sub_category="Biometric doorstep banking & DBT gateway",
            scheme_type="FINANCIAL_SERVICES",
            target_groups=["unbanked_citizens", "rural_residents", "seniors"],
            goals=["financial_inclusion", "emergency_support"],
            gender="all",
            benefit_summary="Zero-paperwork biometric savings account opened at doorstep through Gramin Dak Sevaks, providing AePS cash withdrawal, DBT reception, and bill payments.",
            verification_status="REVIEW_REQUIRED",
            source_authority="India Post Payments Bank",
            official_url="https://www.ippbonline.com/",
            keywords=["IPPB", "doorstep banking postman", "india post payments bank"]
        )
    ]
