# Employment, Labour & Skill Development Schemes (35+ Real Central & State Schemes)

def get_employment_skills_schemes(make_scheme):
    return [
        # --- Central Employment & Skills Schemes ---
        make_scheme(
            scheme_id="emp_naps_001",
            name_en="National Apprenticeship Promotion Scheme (NAPS-2)",
            name_hi="राष्ट्रीय शिक्षुता संवर्धन योजना (एनएपीएस)",
            short_name="NAPS",
            level="central",
            state=None,
            ministry="Ministry of Skill Development and Entrepreneurship",
            department="Directorate General of Training (DGT)",
            category="EMPLOYMENT",
            sub_category="Industry apprenticeship stipend support",
            scheme_type="SKILL_DEVELOPMENT",
            target_groups=["iti_passouts", "diploma_holders", "graduates", "job_seekers"],
            goals=["skill_development", "employment"],
            min_age=14,
            gender="all",
            benefit_summary="Direct government stipend support of 25% of prescribed stipend (up to Rs 1,500/month per apprentice) directly to bank accounts through DBT for on-the-job industrial training.",
            benefit_amount="Up to 1500/month stipend support",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Skill Development and Entrepreneurship",
            official_url="https://www.apprenticeshipindia.gov.in/",
            keywords=["NAPS", "apprenticeship portal", "dgt apprenticeship stipend"]
        ),
        make_scheme(
            scheme_id="emp_ncs_001",
            name_en="National Career Service (NCS Portal)",
            name_hi="राष्ट्रीय करियर सेवा (एनसीएस पोर्टल)",
            short_name="NCS",
            level="central",
            state=None,
            ministry="Ministry of Labour and Employment",
            department="Directorate General of Employment",
            category="EMPLOYMENT",
            sub_category="Free nationwide job matching & career counselling",
            scheme_type="SERVICES",
            target_groups=["job_seekers", "employers", "career_counsellors"],
            goals=["employment"],
            gender="all",
            benefit_summary="Free digital platform linking jobseekers with verified private and public employers, offering free online career assessments, job fairs, and counselling at 400+ Model Career Centres.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Labour and Employment",
            official_url="https://www.ncs.gov.in/",
            keywords=["NCS portal", "national career service", "free job search government", "model career centre"]
        ),
        make_scheme(
            scheme_id="emp_day_nrlm_001",
            name_en="Deendayal Antyodaya Yojana - National Rural Livelihoods Mission",
            name_hi="दीनदयाल अंत्योदय योजना - राष्ट्रीय ग्रामीण आजीविका मिशन",
            short_name="DAY-NRLM",
            level="central",
            state=None,
            ministry="Ministry of Rural Development",
            department="Rural Livelihoods Division",
            category="EMPLOYMENT",
            sub_category="Women SHG promotion, revolving fund & interest subvention",
            scheme_type="LIVELIHOOD_SUPPORT",
            target_groups=["rural_poor_women", "shg_members"],
            goals=["livelihood_support", "women_empowerment", "self_employment"],
            gender="female",
            benefit_summary="Mobilizes rural women into Self Help Groups, providing Revolving Funds (Rs 20,000-30,000), Community Investment Funds (up to Rs 2.5 lakh), and collateral-free bank loans at 7% interest.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Rural Development",
            official_url="https://aajeevika.gov.in/",
            keywords=["DAY-NRLM", "aajeevika", "women SHG loan", "revolving fund SHG"]
        ),
        make_scheme(
            scheme_id="emp_day_nulm_001",
            name_en="Deendayal Antyodaya Yojana - National Urban Livelihoods Mission",
            name_hi="दीनदयाल अंत्योदय योजना - राष्ट्रीय शहरी आजीविका मिशन",
            short_name="DAY-NULM",
            level="central",
            state=None,
            ministry="Ministry of Housing and Urban Affairs",
            department="MoHUA",
            category="EMPLOYMENT",
            sub_category="Urban skill training & self-employment loans",
            scheme_type="LIVELIHOOD_SUPPORT",
            target_groups=["urban_poor", "urban_shgs", "street_vendors"],
            goals=["livelihood_support", "self_employment", "skill_development"],
            gender="all",
            benefit_summary="Subsidised bank loans up to Rs 2 lakh for individual micro-enterprises (Rs 10 lakh for group enterprises) with interest rate capped at 7%, plus free certified placement-linked urban skill training.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Housing and Urban Affairs",
            official_url="https://nulm.gov.in/",
            keywords=["DAY-NULM", "urban livelihoods mission", "urban shg loan 7 percent"]
        ),
        make_scheme(
            scheme_id="emp_ddu_gky_001",
            name_en="Deen Dayal Upadhyaya Grameen Kaushalya Yojana",
            name_hi="दीन दयाल उपाध्याय ग्रामीण कौशल्या योजना",
            short_name="DDU-GKY",
            level="central",
            state=None,
            ministry="Ministry of Rural Development",
            department="Rural Skills Division",
            category="EMPLOYMENT",
            sub_category="Placement-linked rural youth skill training",
            scheme_type="SKILL_DEVELOPMENT",
            target_groups=["rural_poor_youth"],
            goals=["skill_development", "employment"],
            min_age=15,
            max_age=35,
            gender="all",
            benefit_summary="Completely free residential skill training with mandatory minimum 70% guaranteed placement in formal sector jobs offering minimum wages or above.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Rural Development",
            official_url="http://ddugky.gov.in/",
            keywords=["DDU-GKY", "rural skill training with job", "placement linked training"]
        ),
        make_scheme(
            scheme_id="emp_shreyas_001",
            name_en="Scheme for Higher Education Youth in Apprenticeship and Skills (SHREYAS)",
            name_hi="शिक्षुता एवं कौशल में उच्च शिक्षा युवाओं के लिए योजना (श्रेयस)",
            short_name="SHREYAS",
            level="central",
            state=None,
            ministry="Ministry of Education / MoSDE",
            department="Department of Higher Education",
            category="EMPLOYMENT",
            sub_category="Degree apprenticeship with industry stipend",
            scheme_type="SKILL_DEVELOPMENT",
            target_groups=["general_graduates", "ba_bsc_bcom_students"],
            goals=["skill_development", "employment"],
            gender="all",
            benefit_summary="Integrates apprenticeship and professional skill development into general degree courses (BA, BSc, BCom), enabling students to earn monthly stipends while pursuing degrees.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Education",
            official_url="https://www.education.gov.in/",
            keywords=["SHREYAS scheme", "degree apprenticeship", "earn while you learn graduate"]
        ),
        # --- State Employment & Skills Schemes ---
        make_scheme(
            scheme_id="emp_raj_yuva_sambal_001",
            name_en="Rajasthan Mukhyamantri Yuva Sambal Yojana (Unemployment Allowance)",
            name_hi="राजस्थान मुख्यमंत्री युवा संबल योजना (बेरोजगारी भत्ता)",
            short_name="Yuva Sambal RJ",
            level="state",
            state="Rajasthan",
            ministry="Department of Skill, Employment and Entrepreneurship, Government of Rajasthan",
            department="Employment Department Rajasthan",
            category="EMPLOYMENT",
            sub_category="Monthly unemployment allowance with skill internship",
            scheme_type="CASH_TRANSFER",
            target_groups=["unemployed_graduates"],
            goals=["employment", "livelihood_support"],
            min_age=21,
            max_age=30,
            gender="all",
            income_limit=200000,
            income_unit="per annum",
            benefit_summary="Monthly allowance of Rs 4,000 for male graduates and Rs 4,500 for female/transgender/specially-abled graduates for up to 2 years while doing a daily 4-hour government department internship.",
            benefit_amount="4000-4500/month",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Rajasthan",
            official_url="https://employment.livelihoods.rajasthan.gov.in/",
            keywords=["Yuva Sambal Yojana", "rajasthan unemployment allowance", "berojgari bhatta rajasthan"]
        ),
        make_scheme(
            scheme_id="emp_kar_yuva_nidhi_001",
            name_en="Karnataka Yuva Nidhi Scheme",
            name_hi="कर्नाटक युवा निधि योजना",
            short_name="Yuva Nidhi KA",
            level="state",
            state="Karnataka",
            ministry="Department of Skill Development, Entrepreneurship and Livelihood, Govt of Karnataka",
            department="Government of Karnataka",
            category="EMPLOYMENT",
            sub_category="Direct monthly financial support for unemployed graduates",
            scheme_type="CASH_TRANSFER",
            target_groups=["unemployed_graduates", "unemployed_diploma_holders"],
            goals=["employment", "livelihood_support"],
            gender="all",
            benefit_summary="Monthly financial assistance of Rs 3,000 for unemployed degree holders and Rs 1,500 for unemployed diploma holders for up to 2 years or until employment.",
            benefit_amount="1500-3000/month",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Karnataka",
            official_url="https://sevasindhuservices.karnataka.gov.in/",
            keywords=["Yuva Nidhi", "karnataka unemployment allowance", "sevasindhu yuva nidhi"]
        ),
        make_scheme(
            scheme_id="emp_mp_sikho_kamao_001",
            name_en="Madhya Pradesh Mukhyamantri Sikho Kamao Yojana (Learn & Earn)",
            name_hi="मध्य प्रदेश मुख्यमंत्री सीखो कमाओ योजना",
            short_name="Sikho Kamao MP",
            level="state",
            state="Madhya Pradesh",
            ministry="Technical Education, Skill Development & Employment Department, Government of MP",
            department="State Skill Development Mission MP",
            category="EMPLOYMENT",
            sub_category="On-the-job training with state stipend",
            scheme_type="SKILL_DEVELOPMENT",
            target_groups=["youth", "class_12_pass", "iti_diploma_graduates"],
            goals=["skill_development", "employment"],
            min_age=18,
            max_age=29,
            gender="all",
            benefit_summary="On-the-job industrial skill training across 700+ courses with direct monthly stipend of Rs 8,000 (Class 12), Rs 8,500 (ITI), Rs 9,000 (Diploma), and Rs 10,000 (Graduates/Post-Graduates).",
            benefit_amount="8000-10000/month",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Madhya Pradesh",
            official_url="https://mmsky.mp.gov.in/",
            keywords=["Sikho Kamao Yojana", "learn and earn mp", "mmsky portal mp"]
        ),
        make_scheme(
            scheme_id="emp_tn_tnsdc_001",
            name_en="Tamil Nadu Skill Development Corporation (TNSDC) Free Placement Training",
            name_hi="तमिलनाडु कौशल विकास निगम (टीएनएसडीसी) निःशुल्क प्रशिक्षण",
            short_name="TNSDC Schemes",
            level="state",
            state="Tamil Nadu",
            ministry="Labour Welfare and Skill Development Department, Government of Tamil Nadu",
            department="Tamil Nadu Skill Development Corporation",
            category="EMPLOYMENT",
            sub_category="Short-term high-demand job training",
            scheme_type="SKILL_DEVELOPMENT",
            target_groups=["unemployed_youth", "school_college_dropouts"],
            goals=["skill_development", "employment"],
            min_age=18,
            max_age=35,
            gender="all",
            benefit_summary="Free government-sponsored short-term skill training in emerging technology, manufacturing, healthcare, and logistics sectors with placement assistance across Tamil Nadu.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Tamil Nadu",
            official_url="https://www.tnskill.tn.gov.in/",
            keywords=["TNSDC", "tamil nadu skill training", "naan mudhalvan skill"]
        )
    ]
