# Women, Girl Child & Family Welfare Schemes (40+ Real Central & State Schemes)

def get_women_child_schemes(make_scheme):
    return [
        # --- Central Women & Child Welfare Schemes ---
        make_scheme(
            scheme_id="wmn_mssc_001",
            name_en="Mahila Samman Savings Certificate",
            name_hi="महिला सम्मान बचत प्रमाण पत्र",
            short_name="MSSC",
            level="central",
            state=None,
            ministry="Ministry of Finance",
            department="Department of Economic Affairs / India Post & Banks",
            category="SAVINGS",
            sub_category="Women fixed deposit certificate",
            scheme_type="SAVINGS",
            target_groups=["women", "girls"],
            goals=["short_term_savings", "women_empowerment"],
            gender="female",
            minimum_contribution=1000,
            maximum_contribution=200000,
            contribution_frequency="one-time",
            lock_in="2 years",
            maturity="2 years",
            interest_rate="7.5% p.a. compounded quarterly",
            return_type="fixed_govt_notified",
            benefit_summary="Two-year fixed deposit scheme offering a high guaranteed 7.5% p.a. interest rate for women and minor girls (account opened via guardian).",
            tax_benefit="TDS rules apply under IT Act",
            liquidity_level="medium",
            withdrawal_rules="Partial withdrawal up to 40% of eligible balance allowed after 1 year from account opening.",
            verification_status="VERIFIED",
            source_authority="Department of Economic Affairs / India Post",
            official_url="https://www.indiapost.gov.in/Financial/pages/content/post-office-saving-schemes.aspx",
            keywords=["MSSC", "mahila samman", "women fixed deposit", "post office women scheme"]
        ),
        make_scheme(
            scheme_id="wmn_ujjwala_001",
            name_en="Pradhan Mantri Ujjwala Yojana (Ujjwala 2.0)",
            name_hi="प्रधानमंत्री उज्ज्वला योजना (उज्ज्वला 2.0)",
            short_name="PMUY",
            level="central",
            state=None,
            ministry="Ministry of Petroleum and Natural Gas",
            department="Ministry of Petroleum and Natural Gas",
            category="WOMEN",
            sub_category="Clean cooking LPG connection grant",
            scheme_type="SUBSIDY",
            target_groups=["poor_women", "bpl_households", "sc_st_women"],
            goals=["women_empowerment", "healthcare"],
            min_age=18,
            gender="female",
            benefit_summary="Deposit-free LPG connection in the name of an adult woman of poor household, with free first refill, hotplate (stove), and targeted cylinder subsidy.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Petroleum and Natural Gas",
            official_url="https://www.pmuy.gov.in/",
            keywords=["PMUY", "ujjwala yojana", "free gas cylinder", "lpg connection women"]
        ),
        make_scheme(
            scheme_id="wmn_sakhi_niwas_001",
            name_en="Sakhi Niwas (Working Women Hostel Scheme)",
            name_hi="सखी निवास (कामकाजी महिला छात्रावास योजना)",
            short_name="Sakhi Niwas",
            level="central",
            state=None,
            ministry="Ministry of Women and Child Development",
            department="Mission Shakti (Samarthya)",
            category="WOMEN",
            sub_category="Safe urban working women accommodation",
            scheme_type="COMMUNITY_SUPPORT",
            target_groups=["working_women", "trainees", "single_women"],
            goals=["women_empowerment", "employment"],
            min_age=18,
            gender="female",
            benefit_summary="Safe, secure, and affordable hostel accommodation with day care/creche facility for children of working women in urban, semi-urban, and rural areas.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Women and Child Development",
            official_url="https://wcd.nic.in/",
            keywords=["Sakhi Niwas", "working women hostel", "mission shakti hostel"]
        ),
        make_scheme(
            scheme_id="wmn_one_stop_centre_001",
            name_en="One Stop Centre Scheme (Sakhi Centre)",
            name_hi="वन स्टॉप सेंटर (सखी केंद्र योजना)",
            short_name="OSC Sakhi",
            level="central",
            state=None,
            ministry="Ministry of Women and Child Development",
            department="Mission Shakti (Sambal)",
            category="WOMEN",
            sub_category="Emergency support & crisis redressal",
            scheme_type="SERVICES",
            target_groups=["women_in_distress", "violence_affected_women"],
            goals=["women_empowerment", "emergency_support"],
            gender="female",
            benefit_summary="Integrated single-window support providing emergency response, medical aid, legal assistance, psycho-social counselling, and temporary shelter (5 days) for women facing violence.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Women and Child Development",
            official_url="https://wcd.nic.in/",
            keywords=["One Stop Centre", "sakhi centre", "women helpline 181", "violence redressal"]
        ),
        make_scheme(
            scheme_id="wmn_poshan_2_001",
            name_en="Mission Saksham Anganwadi and Poshan 2.0",
            name_hi="सक्षम आंगनवाड़ी एवं पोषण 2.0",
            short_name="Poshan 2.0",
            level="central",
            state=None,
            ministry="Ministry of Women and Child Development",
            department="MWCD",
            category="CHILD_WELFARE",
            sub_category="Supplementary nutrition & early childhood education",
            scheme_type="SERVICES",
            target_groups=["pregnant_women", "lactating_mothers", "children_0_6_years", "adolescent_girls"],
            goals=["child_education", "healthcare"],
            min_age=0,
            max_age=6,
            gender="all",
            benefit_summary="Supplementary nutrition, growth monitoring, preschool non-formal education, and immunization support delivered through nationwide Anganwadi Centres.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Women and Child Development",
            official_url="https://poshanabhiyaan.gov.in/",
            keywords=["Poshan 2.0", "anganwadi services", "supplementary nutrition", "malnutrition support"]
        ),
        make_scheme(
            scheme_id="chld_mission_vatsalya_001",
            name_en="Mission Vatsalya (Child Protection Services)",
            name_hi="मिशन वात्सल्य (बाल संरक्षण सेवा योजना)",
            short_name="Mission Vatsalya",
            level="central",
            state=None,
            ministry="Ministry of Women and Child Development",
            department="MWCD",
            category="CHILD_WELFARE",
            sub_category="Care, protection & foster care sponsorship",
            scheme_type="SOCIAL_ASSISTANCE",
            target_groups=["orphans", "children_in_need_of_care", "street_children"],
            goals=["child_education", "family_support"],
            min_age=0,
            max_age=18,
            gender="all",
            benefit_summary="Institutional and non-institutional care (adoption, foster care, sponsorship of Rs 4,000/month per child) for children in difficult circumstances and distress.",
            benefit_amount="4000/month/child",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Women and Child Development",
            official_url="https://cara.wcd.gov.in/",
            keywords=["Mission Vatsalya", "child protection", "foster care grant", "orphan sponsorship"]
        ),
        make_scheme(
            scheme_id="chld_pm_cares_children_001",
            name_en="PM CARES for Children Scheme",
            name_hi="पीएम केयर्स फॉर चिल्ड्रन योजना",
            short_name="PM CARES Children",
            level="central",
            state=None,
            ministry="Ministry of Women and Child Development",
            department="MWCD / PM CARES Fund",
            category="CHILD_WELFARE",
            sub_category="Comprehensive support for covid-orphaned children",
            scheme_type="SOCIAL_ASSISTANCE",
            target_groups=["covid_orphaned_children"],
            goals=["child_education", "healthcare", "long_term_savings"],
            min_age=0,
            max_age=23,
            gender="all",
            benefit_summary="Rs 10 lakh corpus fund created in post office for each orphaned child maturing at age 23, free school/higher education admission, Rs 20,000 annual scholarship, and Ayushman Bharat health cover.",
            benefit_amount="Rs 10 Lakh corpus at 23",
            verification_status="REVIEW_REQUIRED",
            source_authority="PM CARES / Ministry of Women and Child Development",
            official_url="https://pmcaresforchildren.in/",
            keywords=["PM CARES children", "covid orphan scheme", "10 lakh child fund"]
        ),
        make_scheme(
            scheme_id="wmn_step_scheme_001",
            name_en="Support to Training and Employment Programme for Women (STEP)",
            name_hi="महिलाओं के लिए प्रशिक्षण एवं रोजगार सहायता कार्यक्रम (स्टेप)",
            short_name="STEP Scheme",
            level="central",
            state=None,
            ministry="Ministry of Women and Child Development",
            department="MWCD",
            category="WOMEN",
            sub_category="Skill training for self-employment",
            scheme_type="SKILL_DEVELOPMENT",
            target_groups=["marginalised_women", "rural_urban_poor_women"],
            goals=["women_empowerment", "skill_development", "self_employment"],
            min_age=16,
            gender="female",
            benefit_summary="Employability skill training in agriculture, horticulture, food processing, handlooms, tailoring, and IT to enable women to become self-employed or entrepreneurs.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Women and Child Development",
            official_url="https://wcd.nic.in/",
            keywords=["STEP scheme", "women vocational training", "women self employment"]
        ),
        make_scheme(
            scheme_id="wmn_mahila_ehaat_001",
            name_en="Mahila E-Haat",
            name_hi="महिला ई-हाट",
            short_name="Mahila E-Haat",
            level="central",
            state=None,
            ministry="Ministry of Women and Child Development",
            department="Rashtriya Mahila Kosh (RMK)",
            category="WOMEN",
            sub_category="Online marketing platform for women entrepreneurs",
            scheme_type="MARKETING_SUPPORT",
            target_groups=["women_entrepreneurs", "women_shgs"],
            goals=["women_empowerment", "business"],
            gender="female",
            benefit_summary="Bilingual direct online marketing platform for women entrepreneurs, artisans, and SHGs to display and sell products with zero fee or commission.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Ministry of Women and Child Development",
            official_url="http://mahilaehaat-rmk.gov.in/",
            keywords=["Mahila E-Haat", "women marketplace", "SHG online store"]
        ),
        # --- State Women & Girl Child Schemes ---
        make_scheme(
            scheme_id="wmn_mp_ladli_behna_001",
            name_en="Madhya Pradesh Mukhya Mantri Ladli Behna Yojana",
            name_hi="मध्य प्रदेश मुख्यमंत्री लाड़ली बहना योजना",
            short_name="Ladli Behna MP",
            level="state",
            state="Madhya Pradesh",
            ministry="Women and Child Development Department, Government of MP",
            department="Government of Madhya Pradesh",
            category="WOMEN",
            sub_category="Direct monthly cash transfer to adult women",
            scheme_type="CASH_TRANSFER",
            target_groups=["married_women", "widowed_women", "divorced_women"],
            goals=["women_empowerment", "monthly_income"],
            min_age=21,
            max_age=60,
            gender="female",
            income_limit=250000,
            income_unit="per annum",
            benefit_summary="Direct Benefit Transfer of Rs 1,250 per month into bank accounts of eligible adult women residents of Madhya Pradesh.",
            benefit_amount="1250/month",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Madhya Pradesh",
            official_url="https://cmladlibahna.mp.gov.in/",
            keywords=["Ladli Behna", "madhya pradesh women 1250", "ladli bahna portal"]
        ),
        make_scheme(
            scheme_id="wmn_mah_ladki_bahin_001",
            name_en="Maharashtra Mukhyamantri Majhi Ladki Bahin Yojana",
            name_hi="महाराष्ट्र मुख्यमंत्री माझी लाडकी बहीण योजना",
            short_name="Majhi Ladki Bahin",
            level="state",
            state="Maharashtra",
            ministry="Women and Child Development Department, Government of Maharashtra",
            department="Government of Maharashtra",
            category="WOMEN",
            sub_category="Direct monthly cash assistance for women",
            scheme_type="CASH_TRANSFER",
            target_groups=["women", "unmarried_adult_women", "married_women", "widows"],
            goals=["women_empowerment", "monthly_income"],
            min_age=21,
            max_age=65,
            gender="female",
            income_limit=250000,
            income_unit="per annum",
            benefit_summary="Direct cash assistance of Rs 1,500 per month deposited directly into bank accounts of eligible women aged 21 to 65 years residing in Maharashtra.",
            benefit_amount="1500/month",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Maharashtra",
            official_url="https://ladakibahin.maharashtra.gov.in/",
            keywords=["Majhi Ladki Bahin", "maharashtra 1500 scheme women", "ladki bahin portal"]
        ),
        make_scheme(
            scheme_id="wmn_wb_kanyashree_001",
            name_en="West Bengal Kanyashree Prakalpa (K1 & K2)",
            name_hi="पश्चिम बंगाल कन्याश्री प्रकल्प",
            short_name="Kanyashree WB",
            level="state",
            state="West Bengal",
            ministry="Department of Women and Child Development & Social Welfare, Government of WB",
            department="Government of West Bengal",
            category="WOMEN",
            sub_category="Conditional cash transfer for girl education & delaying marriage",
            scheme_type="CASH_TRANSFER",
            target_groups=["girl_students", "adolescent_girls"],
            goals=["girl_child", "child_education", "marriage"],
            min_age=13,
            max_age=19,
            gender="female",
            benefit_summary="Annual scholarship of Rs 1,000 for unmarried girls in Class 8-12 (K1) and a one-time grant of Rs 25,000 at age 18 (K2) if unmarried and continuing education.",
            benefit_amount="1000/yr + 25000 one-time",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of West Bengal",
            official_url="https://www.wbkanyashree.gov.in/",
            keywords=["Kanyashree", "west bengal girl scholarship", "kanyashree k1 k2"]
        ),
        make_scheme(
            scheme_id="wmn_wb_lakshmir_bhandar_001",
            name_en="West Bengal Lakshmir Bhandar Scheme",
            name_hi="पश्चिम बंगाल लखीर भंडार योजना",
            short_name="Lakshmir Bhandar",
            level="state",
            state="West Bengal",
            ministry="Department of Women & Child Development and Social Welfare, Government of WB",
            department="Government of West Bengal",
            category="WOMEN",
            sub_category="Basic income support for female heads of families",
            scheme_type="CASH_TRANSFER",
            target_groups=["female_household_heads", "sc_st_women", "general_women"],
            goals=["women_empowerment", "monthly_income"],
            min_age=25,
            max_age=60,
            gender="female",
            benefit_summary="Monthly basic income support of Rs 1,200 for SC/ST women and Rs 1,000 for other women who are female heads of families in West Bengal.",
            benefit_amount="1000-1200/month",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of West Bengal",
            official_url="https://socialsecurity.wb.gov.in/",
            keywords=["Lakshmir Bhandar", "west bengal women basic income", "lakhir bhandar"]
        ),
        make_scheme(
            scheme_id="wmn_up_kanya_sumangala_001",
            name_en="Uttar Pradesh Mukhya Mantri Kanya Sumangala Yojana",
            name_hi="उत्तर प्रदेश मुख्यमंत्री कन्या सुमंगला योजना",
            short_name="Kanya Sumangala UP",
            level="state",
            state="Uttar Pradesh",
            ministry="Women and Child Development Department, Government of Uttar Pradesh",
            department="Government of Uttar Pradesh",
            category="WOMEN",
            sub_category="Staged cash incentives from birth to graduation for girl child",
            scheme_type="CASH_TRANSFER",
            target_groups=["girl_child", "parents"],
            goals=["girl_child", "child_education"],
            gender="female",
            income_limit=300000,
            income_unit="per annum",
            benefit_summary="Cash incentives of up to Rs 25,000 distributed in 6 phased stages from birth, vaccinations, Class 1, Class 6, Class 9 admission, to Degree/Diploma enrolment.",
            benefit_amount="Total 25000 in 6 stages",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Uttar Pradesh",
            official_url="https://mksy.up.gov.in/",
            keywords=["Kanya Sumangala", "mksy up portal", "up girl child grant"]
        ),
        make_scheme(
            scheme_id="wmn_raj_rajshree_001",
            name_en="Rajasthan Mukhyamantri Rajshree Yojana",
            name_hi="राजस्थान मुख्यमंत्री राजश्री योजना",
            short_name="Rajshree Rajasthan",
            level="state",
            state="Rajasthan",
            ministry="Women and Child Development Department, Government of Rajasthan",
            department="Government of Rajasthan",
            category="WOMEN",
            sub_category="Staged cash grant for girl child birth & education",
            scheme_type="CASH_TRANSFER",
            target_groups=["girl_child", "mothers"],
            goals=["girl_child", "child_education"],
            gender="female",
            benefit_summary="Financial assistance of up to Rs 50,000 in 6 instalments to parents of girl children born in government hospitals, linked with immunization, Class 1, 6, 10, and 12 schooling.",
            benefit_amount="Total 50000 in 6 stages",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Rajasthan",
            official_url="https://wcd.rajasthan.gov.in/",
            keywords=["Rajshree Yojana", "rajasthan girl child grant 50000", "rajshree portal"]
        ),
        make_scheme(
            scheme_id="wmn_tn_pudhumai_penn_001",
            name_en="Moovalur Ramamirtham Ammaiyar Higher Education Assurance Scheme (Pudhumai Penn - TN)",
            name_hi="पुधुमै पेन उच्च शिक्षा योजना (तमिलनाडु)",
            short_name="Pudhumai Penn TN",
            level="state",
            state="Tamil Nadu",
            ministry="Social Welfare and Women Empowerment Department, Government of Tamil Nadu",
            department="Government of Tamil Nadu",
            category="WOMEN",
            sub_category="Monthly stipend for girl students in higher education",
            scheme_type="CASH_TRANSFER",
            target_groups=["government_school_girls", "college_girls"],
            goals=["girl_child", "child_education"],
            gender="female",
            benefit_summary="Rs 1,000 per month deposited directly into bank accounts of girl students who studied in Government schools (Class 6-12) until they complete their UG degree/diploma.",
            benefit_amount="1000/month",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Tamil Nadu",
            official_url="https://www.pudhumaipenn.tn.gov.in/",
            keywords=["Pudhumai Penn", "tamil nadu 1000 girl college scholarship", "moovalur ramamirtham"]
        ),
        make_scheme(
            scheme_id="wmn_kar_bhagyalakshmi_001",
            name_en="Karnataka Bhagyalakshmi Scheme",
            name_hi="कर्नाटक भाग्यलक्ष्मी योजना",
            short_name="Bhagyalakshmi KA",
            level="state",
            state="Karnataka",
            ministry="Department of Women and Child Development, Government of Karnataka",
            department="Government of Karnataka / LIC",
            category="WOMEN",
            sub_category="BPL girl child endowment & insurance",
            scheme_type="SAVINGS",
            target_groups=["bpl_girl_children"],
            goals=["girl_child", "marriage", "long_term_savings"],
            gender="female",
            guardian_required=True,
            benefit_summary="Financial bond in the name of girl child born in BPL family maturing into substantial corpus at age 18, along with annual scholarships and health cover.",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Karnataka",
            official_url="https://dwcd.karnataka.gov.in/",
            keywords=["Bhagyalakshmi scheme", "karnataka girl bond", "bpl girl insurance"]
        ),
        make_scheme(
            scheme_id="wmn_bihar_kanya_utthan_001",
            name_en="Bihar Mukhyamantri Kanya Utthan Yojana",
            name_hi="बिहार मुख्यमंत्री कन्या उत्थान योजना",
            short_name="Kanya Utthan Bihar",
            level="state",
            state="Bihar",
            ministry="Social Welfare / Education Department, Government of Bihar",
            department="Government of Bihar",
            category="WOMEN",
            sub_category="Cash reward from birth to graduation",
            scheme_type="CASH_TRANSFER",
            target_groups=["girl_child", "female_graduates"],
            goals=["girl_child", "child_education"],
            gender="female",
            benefit_summary="Financial incentives from birth to graduation (including Rs 25,000 upon passing Class 12 unmarried and Rs 50,000 upon graduation for every girl student in Bihar).",
            benefit_amount="Up to 54100 total",
            verification_status="REVIEW_REQUIRED",
            source_authority="Government of Bihar",
            official_url="https://medhasoft.bih.nic.in/",
            keywords=["Kanya Utthan Bihar", "bihar 50000 graduate girl", "medhasoft portal"]
        )
    ]
